package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmMeracct;
import com.aisino.finace.account.entity.TmMeracctExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmMeracctMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmMeracctExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmMeracctExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal iAcctid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmMeracct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmMeracct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmMeracct> selectByExample(TmMeracctExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmMeracct selectByPrimaryKey(BigDecimal iAcctid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmMeracct record,
			@Param("example") TmMeracctExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmMeracct record,
			@Param("example") TmMeracctExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmMeracct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmMeracct record);
}