package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmOrginfo;
import com.aisino.finace.account.entity.TmOrginfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmOrginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int countByExample(TmOrginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int deleteByExample(TmOrginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int deleteByPrimaryKey(String sOrguuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int insert(TmOrginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int insertSelective(TmOrginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    List<TmOrginfo> selectByExample(TmOrginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    TmOrginfo selectByPrimaryKey(String sOrguuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") TmOrginfo record, @Param("example") TmOrginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int updateByExample(@Param("record") TmOrginfo record, @Param("example") TmOrginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int updateByPrimaryKeySelective(TmOrginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM_ORGINFO
     *
     * @mbggenerated Mon May 18 09:26:27 CST 2015
     */
    int updateByPrimaryKey(TmOrginfo record);
}