package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmTerminfo;
import com.aisino.finace.account.entity.TmTerminfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmTerminfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmTerminfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmTerminfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(Long iMercode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmTerminfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmTerminfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmTerminfo> selectByExample(TmTerminfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmTerminfo selectByPrimaryKey(Long iMercode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmTerminfo record,
			@Param("example") TmTerminfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmTerminfo record,
			@Param("example") TmTerminfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmTerminfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmTerminfo record);
}