package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.MlApproveTaskCfg;
import com.aisino.finace.account.entity.MlApproveTaskCfgExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MlApproveTaskCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int countByExample(MlApproveTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int deleteByExample(MlApproveTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int insert(MlApproveTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int insertSelective(MlApproveTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    List<MlApproveTaskCfg> selectByExample(MlApproveTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    MlApproveTaskCfg selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") MlApproveTaskCfg record, @Param("example") MlApproveTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int updateByExample(@Param("record") MlApproveTaskCfg record, @Param("example") MlApproveTaskCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(MlApproveTaskCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_approve_task_cfg
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    int updateByPrimaryKey(MlApproveTaskCfg record);
}