package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmAisinoorginfo;
import com.aisino.finace.account.entity.TmAisinoorginfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmAisinoorginfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmAisinoorginfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmAisinoorginfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(String sOrguuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmAisinoorginfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmAisinoorginfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmAisinoorginfo> selectByExample(TmAisinoorginfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmAisinoorginfo selectByPrimaryKey(String sOrguuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmAisinoorginfo record,
			@Param("example") TmAisinoorginfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmAisinoorginfo record,
			@Param("example") TmAisinoorginfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmAisinoorginfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_AISINOORGINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmAisinoorginfo record);
}