package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmChrinfo;
import com.aisino.finace.account.entity.TmChrinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmChrinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmChrinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmChrinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(String iChrid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmChrinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmChrinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmChrinfo> selectByExample(TmChrinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmChrinfo selectByPrimaryKey(String iChrid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmChrinfo record,
			@Param("example") TmChrinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmChrinfo record,
			@Param("example") TmChrinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmChrinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_CHRINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmChrinfo record);
}