package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmMerservacctdetail;
import com.aisino.finace.account.entity.TmMerservacctdetailExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmMerservacctdetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmMerservacctdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmMerservacctdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(BigDecimal iCardid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmMerservacctdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmMerservacctdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmMerservacctdetail> selectByExample(TmMerservacctdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmMerservacctdetail selectByPrimaryKey(BigDecimal iCardid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmMerservacctdetail record,
			@Param("example") TmMerservacctdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmMerservacctdetail record,
			@Param("example") TmMerservacctdetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmMerservacctdetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmMerservacctdetail record);
}