package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TmMsinfo;
import com.aisino.finace.account.entity.TmMsinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmMsinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int countByExample(TmMsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByExample(TmMsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int deleteByPrimaryKey(String sMsuuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insert(TmMsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int insertSelective(TmMsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	List<TmMsinfo> selectByExample(TmMsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	TmMsinfo selectByPrimaryKey(String sMsuuid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") TmMsinfo record,
			@Param("example") TmMsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByExample(@Param("record") TmMsinfo record,
			@Param("example") TmMsinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKeySelective(TmMsinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MSINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	int updateByPrimaryKey(TmMsinfo record);
}