package com.aisino.finace.account.dao;

import com.aisino.finace.account.entity.TvTradetail;
import com.aisino.finace.account.entity.TvTradetailExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TvTradetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int countByExample(TvTradetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int deleteByExample(TvTradetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal sTrasrlno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int insert(TvTradetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int insertSelective(TvTradetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    List<TvTradetail> selectByExample(TvTradetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    TvTradetail selectByPrimaryKey(BigDecimal sTrasrlno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int updateByExampleSelective(@Param("record") TvTradetail record, @Param("example") TvTradetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int updateByExample(@Param("record") TvTradetail record, @Param("example") TvTradetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int updateByPrimaryKeySelective(TvTradetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    int updateByPrimaryKey(TvTradetail record);
}