package com.aisino.finace.account.entity;

public class MlApproveDealInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.APP_NO
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private String appNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.DEAL_ID
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private Long dealId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.APP_NO
     *
     * @return the value of ml_approve_deal_info.APP_NO
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public String getAppNo() {
        return appNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.APP_NO
     *
     * @param appNo the value for ml_approve_deal_info.APP_NO
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setAppNo(String appNo) {
        this.appNo = appNo == null ? null : appNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.DEAL_ID
     *
     * @return the value of ml_approve_deal_info.DEAL_ID
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public Long getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.DEAL_ID
     *
     * @param dealId the value for ml_approve_deal_info.DEAL_ID
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setDealId(Long dealId) {
        this.dealId = dealId;
    }
}