package com.aisino.finace.account.entity;

public class MlDictItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.ITEM_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.DICT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.ITEM_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.ITEM_CODE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String itemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.ITEM_VAL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String itemVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.ITEM_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String itemTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Integer seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_dict_item.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.ITEM_ID
     *
     * @return the value of ml_dict_item.ITEM_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.ITEM_ID
     *
     * @param itemId the value for ml_dict_item.ITEM_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.DICT_ID
     *
     * @return the value of ml_dict_item.DICT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.DICT_ID
     *
     * @param dictId the value for ml_dict_item.DICT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.ITEM_DESC
     *
     * @return the value of ml_dict_item.ITEM_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.ITEM_DESC
     *
     * @param itemDesc the value for ml_dict_item.ITEM_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.ITEM_CODE
     *
     * @return the value of ml_dict_item.ITEM_CODE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.ITEM_CODE
     *
     * @param itemCode the value for ml_dict_item.ITEM_CODE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode == null ? null : itemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.ITEM_VAL
     *
     * @return the value of ml_dict_item.ITEM_VAL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getItemVal() {
        return itemVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.ITEM_VAL
     *
     * @param itemVal the value for ml_dict_item.ITEM_VAL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setItemVal(String itemVal) {
        this.itemVal = itemVal == null ? null : itemVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.ITEM_TITLE
     *
     * @return the value of ml_dict_item.ITEM_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.ITEM_TITLE
     *
     * @param itemTitle the value for ml_dict_item.ITEM_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle == null ? null : itemTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.SEQ
     *
     * @return the value of ml_dict_item.SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.SEQ
     *
     * @param seq the value for ml_dict_item.SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.PARENT_ID
     *
     * @return the value of ml_dict_item.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.PARENT_ID
     *
     * @param parentId the value for ml_dict_item.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_dict_item.STATUS
     *
     * @return the value of ml_dict_item.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_dict_item.STATUS
     *
     * @param status the value for ml_dict_item.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}