package com.aisino.finace.account.entity;

import java.util.Date;

public class MlRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.ORG_NO
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String orgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.ROLE_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.ROLE_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.CREATE_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.MODIFY_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role.OPER
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long oper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.ROLE_ID
     *
     * @return the value of ml_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.ROLE_ID
     *
     * @param roleId the value for ml_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.ORG_NO
     *
     * @return the value of ml_role.ORG_NO
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getOrgNo() {
        return orgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.ORG_NO
     *
     * @param orgNo the value for ml_role.ORG_NO
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setOrgNo(String orgNo) {
        this.orgNo = orgNo == null ? null : orgNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.ROLE_NAME
     *
     * @return the value of ml_role.ROLE_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.ROLE_NAME
     *
     * @param roleName the value for ml_role.ROLE_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.ROLE_DESC
     *
     * @return the value of ml_role.ROLE_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.ROLE_DESC
     *
     * @param roleDesc the value for ml_role.ROLE_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.STATUS
     *
     * @return the value of ml_role.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.STATUS
     *
     * @param status the value for ml_role.STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.CREATE_DATE
     *
     * @return the value of ml_role.CREATE_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.CREATE_DATE
     *
     * @param createDate the value for ml_role.CREATE_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.MODIFY_DATE
     *
     * @return the value of ml_role.MODIFY_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.MODIFY_DATE
     *
     * @param modifyDate the value for ml_role.MODIFY_DATE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role.OPER
     *
     * @return the value of ml_role.OPER
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getOper() {
        return oper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role.OPER
     *
     * @param oper the value for ml_role.OPER
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setOper(Long oper) {
        this.oper = oper;
    }
}