package com.aisino.finace.account.entity;

public class MlUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user_role.USER_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_user_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user_role.USER_ID
     *
     * @return the value of ml_user_role.USER_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user_role.USER_ID
     *
     * @param userId the value for ml_user_role.USER_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_user_role.ROLE_ID
     *
     * @return the value of ml_user_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_user_role.ROLE_ID
     *
     * @param roleId the value for ml_user_role.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}