package com.aisino.finace.account.entity;

import java.util.Date;

public class TmChrinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.I_CHRID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String iChrid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_CHRNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sChrname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_NKNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sNkname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_CHRREGMER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sChrregmer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_CHRCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sChrcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sPasswd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_PID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sPid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMicromsgno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_CHRADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sChraddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_GENDER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.D_BIRTHDAY
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date dBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_CHRSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sChrstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_RELORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sRelorg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.D_CHRREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date dChrregdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_COMNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sComname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sIseffect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_CHRINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date tsSysupdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.I_CHRID
	 * @return  the value of TM_CHRINFO.I_CHRID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getiChrid() {
		return iChrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.I_CHRID
	 * @param iChrid  the value for TM_CHRINFO.I_CHRID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setiChrid(String iChrid) {
		this.iChrid = iChrid == null ? null : iChrid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_CHRNAME
	 * @return  the value of TM_CHRINFO.S_CHRNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsChrname() {
		return sChrname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_CHRNAME
	 * @param sChrname  the value for TM_CHRINFO.S_CHRNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsChrname(String sChrname) {
		this.sChrname = sChrname == null ? null : sChrname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_NKNAME
	 * @return  the value of TM_CHRINFO.S_NKNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsNkname() {
		return sNkname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_NKNAME
	 * @param sNkname  the value for TM_CHRINFO.S_NKNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsNkname(String sNkname) {
		this.sNkname = sNkname == null ? null : sNkname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_CHRREGMER
	 * @return  the value of TM_CHRINFO.S_CHRREGMER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsChrregmer() {
		return sChrregmer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_CHRREGMER
	 * @param sChrregmer  the value for TM_CHRINFO.S_CHRREGMER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsChrregmer(String sChrregmer) {
		this.sChrregmer = sChrregmer == null ? null : sChrregmer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_CHRCODE
	 * @return  the value of TM_CHRINFO.S_CHRCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsChrcode() {
		return sChrcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_CHRCODE
	 * @param sChrcode  the value for TM_CHRINFO.S_CHRCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsChrcode(String sChrcode) {
		this.sChrcode = sChrcode == null ? null : sChrcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_PASSWD
	 * @return  the value of TM_CHRINFO.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsPasswd() {
		return sPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_PASSWD
	 * @param sPasswd  the value for TM_CHRINFO.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsPasswd(String sPasswd) {
		this.sPasswd = sPasswd == null ? null : sPasswd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_EMAIL
	 * @return  the value of TM_CHRINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsEmail() {
		return sEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_EMAIL
	 * @param sEmail  the value for TM_CHRINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsEmail(String sEmail) {
		this.sEmail = sEmail == null ? null : sEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_PID
	 * @return  the value of TM_CHRINFO.S_PID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsPid() {
		return sPid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_PID
	 * @param sPid  the value for TM_CHRINFO.S_PID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsPid(String sPid) {
		this.sPid = sPid == null ? null : sPid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_MICROMSGNO
	 * @return  the value of TM_CHRINFO.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMicromsgno() {
		return sMicromsgno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_MICROMSGNO
	 * @param sMicromsgno  the value for TM_CHRINFO.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMicromsgno(String sMicromsgno) {
		this.sMicromsgno = sMicromsgno == null ? null : sMicromsgno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_CHRADDR
	 * @return  the value of TM_CHRINFO.S_CHRADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsChraddr() {
		return sChraddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_CHRADDR
	 * @param sChraddr  the value for TM_CHRINFO.S_CHRADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsChraddr(String sChraddr) {
		this.sChraddr = sChraddr == null ? null : sChraddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_GENDER
	 * @return  the value of TM_CHRINFO.S_GENDER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsGender() {
		return sGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_GENDER
	 * @param sGender  the value for TM_CHRINFO.S_GENDER
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsGender(String sGender) {
		this.sGender = sGender == null ? null : sGender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.D_BIRTHDAY
	 * @return  the value of TM_CHRINFO.D_BIRTHDAY
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getdBirthday() {
		return dBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.D_BIRTHDAY
	 * @param dBirthday  the value for TM_CHRINFO.D_BIRTHDAY
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setdBirthday(Date dBirthday) {
		this.dBirthday = dBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_CHRSTATUS
	 * @return  the value of TM_CHRINFO.S_CHRSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsChrstatus() {
		return sChrstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_CHRSTATUS
	 * @param sChrstatus  the value for TM_CHRINFO.S_CHRSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsChrstatus(String sChrstatus) {
		this.sChrstatus = sChrstatus == null ? null : sChrstatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_RELORG
	 * @return  the value of TM_CHRINFO.S_RELORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsRelorg() {
		return sRelorg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_RELORG
	 * @param sRelorg  the value for TM_CHRINFO.S_RELORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsRelorg(String sRelorg) {
		this.sRelorg = sRelorg == null ? null : sRelorg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.D_CHRREGDATE
	 * @return  the value of TM_CHRINFO.D_CHRREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getdChrregdate() {
		return dChrregdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.D_CHRREGDATE
	 * @param dChrregdate  the value for TM_CHRINFO.D_CHRREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setdChrregdate(Date dChrregdate) {
		this.dChrregdate = dChrregdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_REMARK
	 * @return  the value of TM_CHRINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsRemark() {
		return sRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_REMARK
	 * @param sRemark  the value for TM_CHRINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsRemark(String sRemark) {
		this.sRemark = sRemark == null ? null : sRemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_COMNAME
	 * @return  the value of TM_CHRINFO.S_COMNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsComname() {
		return sComname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_COMNAME
	 * @param sComname  the value for TM_CHRINFO.S_COMNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsComname(String sComname) {
		this.sComname = sComname == null ? null : sComname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.S_ISEFFECT
	 * @return  the value of TM_CHRINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsIseffect() {
		return sIseffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.S_ISEFFECT
	 * @param sIseffect  the value for TM_CHRINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsIseffect(String sIseffect) {
		this.sIseffect = sIseffect == null ? null : sIseffect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_CHRINFO.TS_SYSUPDATE
	 * @return  the value of TM_CHRINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getTsSysupdate() {
		return tsSysupdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_CHRINFO.TS_SYSUPDATE
	 * @param tsSysupdate  the value for TM_CHRINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setTsSysupdate(Date tsSysupdate) {
		this.tsSysupdate = tsSysupdate;
	}
}