package com.aisino.finace.account.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TmMeracct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.I_ACCTID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private BigDecimal iAcctid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_ACCTCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sAcctcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Long iMercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_MERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_MERREGADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMerregaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_BIZADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sBizaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sPasswd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_DUTYERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sDutyername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_DUTYERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sDutyerphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMicromsgno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_ACCTSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sAcctstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.D_ACCTREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date dAcctregdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_ACCTREGORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sAcctregorg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_OFSERVORGCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sOfservorgcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_UPPEMERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sUppemercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_BIZCLASS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sBizclass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sIseffect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MERACCT.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date tsSysupdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.I_ACCTID
	 * @return  the value of TM_MERACCT.I_ACCTID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public BigDecimal getiAcctid() {
		return iAcctid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.I_ACCTID
	 * @param iAcctid  the value for TM_MERACCT.I_ACCTID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setiAcctid(BigDecimal iAcctid) {
		this.iAcctid = iAcctid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_ACCTCODE
	 * @return  the value of TM_MERACCT.S_ACCTCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsAcctcode() {
		return sAcctcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_ACCTCODE
	 * @param sAcctcode  the value for TM_MERACCT.S_ACCTCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsAcctcode(String sAcctcode) {
		this.sAcctcode = sAcctcode == null ? null : sAcctcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.I_MERCODE
	 * @return  the value of TM_MERACCT.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Long getiMercode() {
		return iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.I_MERCODE
	 * @param iMercode  the value for TM_MERACCT.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setiMercode(Long iMercode) {
		this.iMercode = iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_MERNAME
	 * @return  the value of TM_MERACCT.S_MERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMername() {
		return sMername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_MERNAME
	 * @param sMername  the value for TM_MERACCT.S_MERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMername(String sMername) {
		this.sMername = sMername == null ? null : sMername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_MERREGADDR
	 * @return  the value of TM_MERACCT.S_MERREGADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMerregaddr() {
		return sMerregaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_MERREGADDR
	 * @param sMerregaddr  the value for TM_MERACCT.S_MERREGADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMerregaddr(String sMerregaddr) {
		this.sMerregaddr = sMerregaddr == null ? null : sMerregaddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_BIZADDR
	 * @return  the value of TM_MERACCT.S_BIZADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsBizaddr() {
		return sBizaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_BIZADDR
	 * @param sBizaddr  the value for TM_MERACCT.S_BIZADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsBizaddr(String sBizaddr) {
		this.sBizaddr = sBizaddr == null ? null : sBizaddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_PASSWD
	 * @return  the value of TM_MERACCT.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsPasswd() {
		return sPasswd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_PASSWD
	 * @param sPasswd  the value for TM_MERACCT.S_PASSWD
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsPasswd(String sPasswd) {
		this.sPasswd = sPasswd == null ? null : sPasswd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_DUTYERNAME
	 * @return  the value of TM_MERACCT.S_DUTYERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsDutyername() {
		return sDutyername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_DUTYERNAME
	 * @param sDutyername  the value for TM_MERACCT.S_DUTYERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsDutyername(String sDutyername) {
		this.sDutyername = sDutyername == null ? null : sDutyername.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_DUTYERPHONE
	 * @return  the value of TM_MERACCT.S_DUTYERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsDutyerphone() {
		return sDutyerphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_DUTYERPHONE
	 * @param sDutyerphone  the value for TM_MERACCT.S_DUTYERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsDutyerphone(String sDutyerphone) {
		this.sDutyerphone = sDutyerphone == null ? null : sDutyerphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_MICROMSGNO
	 * @return  the value of TM_MERACCT.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMicromsgno() {
		return sMicromsgno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_MICROMSGNO
	 * @param sMicromsgno  the value for TM_MERACCT.S_MICROMSGNO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMicromsgno(String sMicromsgno) {
		this.sMicromsgno = sMicromsgno == null ? null : sMicromsgno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_ACCTSTATUS
	 * @return  the value of TM_MERACCT.S_ACCTSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsAcctstatus() {
		return sAcctstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_ACCTSTATUS
	 * @param sAcctstatus  the value for TM_MERACCT.S_ACCTSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsAcctstatus(String sAcctstatus) {
		this.sAcctstatus = sAcctstatus == null ? null : sAcctstatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.D_ACCTREGDATE
	 * @return  the value of TM_MERACCT.D_ACCTREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getdAcctregdate() {
		return dAcctregdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.D_ACCTREGDATE
	 * @param dAcctregdate  the value for TM_MERACCT.D_ACCTREGDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setdAcctregdate(Date dAcctregdate) {
		this.dAcctregdate = dAcctregdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_ACCTREGORG
	 * @return  the value of TM_MERACCT.S_ACCTREGORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsAcctregorg() {
		return sAcctregorg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_ACCTREGORG
	 * @param sAcctregorg  the value for TM_MERACCT.S_ACCTREGORG
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsAcctregorg(String sAcctregorg) {
		this.sAcctregorg = sAcctregorg == null ? null : sAcctregorg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_OFSERVORGCODE
	 * @return  the value of TM_MERACCT.S_OFSERVORGCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsOfservorgcode() {
		return sOfservorgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_OFSERVORGCODE
	 * @param sOfservorgcode  the value for TM_MERACCT.S_OFSERVORGCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsOfservorgcode(String sOfservorgcode) {
		this.sOfservorgcode = sOfservorgcode == null ? null : sOfservorgcode
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_UPPEMERCODE
	 * @return  the value of TM_MERACCT.S_UPPEMERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsUppemercode() {
		return sUppemercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_UPPEMERCODE
	 * @param sUppemercode  the value for TM_MERACCT.S_UPPEMERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsUppemercode(String sUppemercode) {
		this.sUppemercode = sUppemercode == null ? null : sUppemercode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_BIZCLASS
	 * @return  the value of TM_MERACCT.S_BIZCLASS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsBizclass() {
		return sBizclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_BIZCLASS
	 * @param sBizclass  the value for TM_MERACCT.S_BIZCLASS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsBizclass(String sBizclass) {
		this.sBizclass = sBizclass == null ? null : sBizclass.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.S_ISEFFECT
	 * @return  the value of TM_MERACCT.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsIseffect() {
		return sIseffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.S_ISEFFECT
	 * @param sIseffect  the value for TM_MERACCT.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsIseffect(String sIseffect) {
		this.sIseffect = sIseffect == null ? null : sIseffect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MERACCT.TS_SYSUPDATE
	 * @return  the value of TM_MERACCT.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getTsSysupdate() {
		return tsSysupdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MERACCT.TS_SYSUPDATE
	 * @param tsSysupdate  the value for TM_MERACCT.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setTsSysupdate(Date tsSysupdate) {
		this.tsSysupdate = tsSysupdate;
	}
}