package com.aisino.finace.account.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TmMerservacctdetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public TmMerservacctdetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andICardidIsNull() {
			addCriterion("I_CARDID is null");
			return (Criteria) this;
		}

		public Criteria andICardidIsNotNull() {
			addCriterion("I_CARDID is not null");
			return (Criteria) this;
		}

		public Criteria andICardidEqualTo(BigDecimal value) {
			addCriterion("I_CARDID =", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidNotEqualTo(BigDecimal value) {
			addCriterion("I_CARDID <>", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidGreaterThan(BigDecimal value) {
			addCriterion("I_CARDID >", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("I_CARDID >=", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidLessThan(BigDecimal value) {
			addCriterion("I_CARDID <", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidLessThanOrEqualTo(BigDecimal value) {
			addCriterion("I_CARDID <=", value, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidIn(List<BigDecimal> values) {
			addCriterion("I_CARDID in", values, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidNotIn(List<BigDecimal> values) {
			addCriterion("I_CARDID not in", values, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("I_CARDID between", value1, value2, "iCardid");
			return (Criteria) this;
		}

		public Criteria andICardidNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("I_CARDID not between", value1, value2, "iCardid");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIsNull() {
			addCriterion("S_ACCTCODE is null");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIsNotNull() {
			addCriterion("S_ACCTCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeEqualTo(String value) {
			addCriterion("S_ACCTCODE =", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotEqualTo(String value) {
			addCriterion("S_ACCTCODE <>", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeGreaterThan(String value) {
			addCriterion("S_ACCTCODE >", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_ACCTCODE >=", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLessThan(String value) {
			addCriterion("S_ACCTCODE <", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLessThanOrEqualTo(String value) {
			addCriterion("S_ACCTCODE <=", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLike(String value) {
			addCriterion("S_ACCTCODE like", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotLike(String value) {
			addCriterion("S_ACCTCODE not like", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIn(List<String> values) {
			addCriterion("S_ACCTCODE in", values, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotIn(List<String> values) {
			addCriterion("S_ACCTCODE not in", values, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeBetween(String value1, String value2) {
			addCriterion("S_ACCTCODE between", value1, value2, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotBetween(String value1, String value2) {
			addCriterion("S_ACCTCODE not between", value1, value2, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andICardnoIsNull() {
			addCriterion("I_CARDNO is null");
			return (Criteria) this;
		}

		public Criteria andICardnoIsNotNull() {
			addCriterion("I_CARDNO is not null");
			return (Criteria) this;
		}

		public Criteria andICardnoEqualTo(BigDecimal value) {
			addCriterion("I_CARDNO =", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoNotEqualTo(BigDecimal value) {
			addCriterion("I_CARDNO <>", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoGreaterThan(BigDecimal value) {
			addCriterion("I_CARDNO >", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("I_CARDNO >=", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoLessThan(BigDecimal value) {
			addCriterion("I_CARDNO <", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoLessThanOrEqualTo(BigDecimal value) {
			addCriterion("I_CARDNO <=", value, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoIn(List<BigDecimal> values) {
			addCriterion("I_CARDNO in", values, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoNotIn(List<BigDecimal> values) {
			addCriterion("I_CARDNO not in", values, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("I_CARDNO between", value1, value2, "iCardno");
			return (Criteria) this;
		}

		public Criteria andICardnoNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("I_CARDNO not between", value1, value2, "iCardno");
			return (Criteria) this;
		}

		public Criteria andSCardtypeIsNull() {
			addCriterion("S_CARDTYPE is null");
			return (Criteria) this;
		}

		public Criteria andSCardtypeIsNotNull() {
			addCriterion("S_CARDTYPE is not null");
			return (Criteria) this;
		}

		public Criteria andSCardtypeEqualTo(String value) {
			addCriterion("S_CARDTYPE =", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeNotEqualTo(String value) {
			addCriterion("S_CARDTYPE <>", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeGreaterThan(String value) {
			addCriterion("S_CARDTYPE >", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeGreaterThanOrEqualTo(String value) {
			addCriterion("S_CARDTYPE >=", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeLessThan(String value) {
			addCriterion("S_CARDTYPE <", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeLessThanOrEqualTo(String value) {
			addCriterion("S_CARDTYPE <=", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeLike(String value) {
			addCriterion("S_CARDTYPE like", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeNotLike(String value) {
			addCriterion("S_CARDTYPE not like", value, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeIn(List<String> values) {
			addCriterion("S_CARDTYPE in", values, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeNotIn(List<String> values) {
			addCriterion("S_CARDTYPE not in", values, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeBetween(String value1, String value2) {
			addCriterion("S_CARDTYPE between", value1, value2, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardtypeNotBetween(String value1, String value2) {
			addCriterion("S_CARDTYPE not between", value1, value2, "sCardtype");
			return (Criteria) this;
		}

		public Criteria andSCardstatusIsNull() {
			addCriterion("S_CARDSTATUS is null");
			return (Criteria) this;
		}

		public Criteria andSCardstatusIsNotNull() {
			addCriterion("S_CARDSTATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSCardstatusEqualTo(String value) {
			addCriterion("S_CARDSTATUS =", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusNotEqualTo(String value) {
			addCriterion("S_CARDSTATUS <>", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusGreaterThan(String value) {
			addCriterion("S_CARDSTATUS >", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusGreaterThanOrEqualTo(String value) {
			addCriterion("S_CARDSTATUS >=", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusLessThan(String value) {
			addCriterion("S_CARDSTATUS <", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusLessThanOrEqualTo(String value) {
			addCriterion("S_CARDSTATUS <=", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusLike(String value) {
			addCriterion("S_CARDSTATUS like", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusNotLike(String value) {
			addCriterion("S_CARDSTATUS not like", value, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusIn(List<String> values) {
			addCriterion("S_CARDSTATUS in", values, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusNotIn(List<String> values) {
			addCriterion("S_CARDSTATUS not in", values, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusBetween(String value1, String value2) {
			addCriterion("S_CARDSTATUS between", value1, value2, "sCardstatus");
			return (Criteria) this;
		}

		public Criteria andSCardstatusNotBetween(String value1, String value2) {
			addCriterion("S_CARDSTATUS not between", value1, value2,
					"sCardstatus");
			return (Criteria) this;
		}

		public Criteria andIAcctidIsNull() {
			addCriterion("I_ACCTID is null");
			return (Criteria) this;
		}

		public Criteria andIAcctidIsNotNull() {
			addCriterion("I_ACCTID is not null");
			return (Criteria) this;
		}

		public Criteria andIAcctidEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID =", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID <>", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidGreaterThan(BigDecimal value) {
			addCriterion("I_ACCTID >", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID >=", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidLessThan(BigDecimal value) {
			addCriterion("I_ACCTID <", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidLessThanOrEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID <=", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidIn(List<BigDecimal> values) {
			addCriterion("I_ACCTID in", values, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotIn(List<BigDecimal> values) {
			addCriterion("I_ACCTID not in", values, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("I_ACCTID between", value1, value2, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("I_ACCTID not between", value1, value2, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceIsNull() {
			addCriterion("F_RMBBALANCE is null");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceIsNotNull() {
			addCriterion("F_RMBBALANCE is not null");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceEqualTo(BigDecimal value) {
			addCriterion("F_RMBBALANCE =", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceNotEqualTo(BigDecimal value) {
			addCriterion("F_RMBBALANCE <>", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceGreaterThan(BigDecimal value) {
			addCriterion("F_RMBBALANCE >", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("F_RMBBALANCE >=", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceLessThan(BigDecimal value) {
			addCriterion("F_RMBBALANCE <", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("F_RMBBALANCE <=", value, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceIn(List<BigDecimal> values) {
			addCriterion("F_RMBBALANCE in", values, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceNotIn(List<BigDecimal> values) {
			addCriterion("F_RMBBALANCE not in", values, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("F_RMBBALANCE between", value1, value2, "fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFRmbbalanceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("F_RMBBALANCE not between", value1, value2,
					"fRmbbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceIsNull() {
			addCriterion("F_POINTBALANCE is null");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceIsNotNull() {
			addCriterion("F_POINTBALANCE is not null");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceEqualTo(BigDecimal value) {
			addCriterion("F_POINTBALANCE =", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceNotEqualTo(BigDecimal value) {
			addCriterion("F_POINTBALANCE <>", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceGreaterThan(BigDecimal value) {
			addCriterion("F_POINTBALANCE >", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("F_POINTBALANCE >=", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceLessThan(BigDecimal value) {
			addCriterion("F_POINTBALANCE <", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("F_POINTBALANCE <=", value, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceIn(List<BigDecimal> values) {
			addCriterion("F_POINTBALANCE in", values, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceNotIn(List<BigDecimal> values) {
			addCriterion("F_POINTBALANCE not in", values, "fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("F_POINTBALANCE between", value1, value2,
					"fPointbalance");
			return (Criteria) this;
		}

		public Criteria andFPointbalanceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("F_POINTBALANCE not between", value1, value2,
					"fPointbalance");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNull() {
			addCriterion("S_ISEFFECT is null");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNotNull() {
			addCriterion("S_ISEFFECT is not null");
			return (Criteria) this;
		}

		public Criteria andSIseffectEqualTo(String value) {
			addCriterion("S_ISEFFECT =", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotEqualTo(String value) {
			addCriterion("S_ISEFFECT <>", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThan(String value) {
			addCriterion("S_ISEFFECT >", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT >=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThan(String value) {
			addCriterion("S_ISEFFECT <", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT <=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLike(String value) {
			addCriterion("S_ISEFFECT like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotLike(String value) {
			addCriterion("S_ISEFFECT not like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectIn(List<String> values) {
			addCriterion("S_ISEFFECT in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotIn(List<String> values) {
			addCriterion("S_ISEFFECT not in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT not between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNull() {
			addCriterion("TS_SYSUPDATE is null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNotNull() {
			addCriterion("TS_SYSUPDATE is not null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE =", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <>", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThan(Date value) {
			addCriterion("TS_SYSUPDATE >", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE >=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThan(Date value) {
			addCriterion("TS_SYSUPDATE <", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE not in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE between", value1, value2, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE not between", value1, value2,
					"tsSysupdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERSERVACCTDETAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MERSERVACCTDETAIL
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 14:43:00 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}