package com.aisino.finace.account.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TmMeracctExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public TmMeracctExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIAcctidIsNull() {
			addCriterion("I_ACCTID is null");
			return (Criteria) this;
		}

		public Criteria andIAcctidIsNotNull() {
			addCriterion("I_ACCTID is not null");
			return (Criteria) this;
		}

		public Criteria andIAcctidEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID =", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID <>", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidGreaterThan(BigDecimal value) {
			addCriterion("I_ACCTID >", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID >=", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidLessThan(BigDecimal value) {
			addCriterion("I_ACCTID <", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidLessThanOrEqualTo(BigDecimal value) {
			addCriterion("I_ACCTID <=", value, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidIn(List<BigDecimal> values) {
			addCriterion("I_ACCTID in", values, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotIn(List<BigDecimal> values) {
			addCriterion("I_ACCTID not in", values, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("I_ACCTID between", value1, value2, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andIAcctidNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("I_ACCTID not between", value1, value2, "iAcctid");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIsNull() {
			addCriterion("S_ACCTCODE is null");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIsNotNull() {
			addCriterion("S_ACCTCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeEqualTo(String value) {
			addCriterion("S_ACCTCODE =", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotEqualTo(String value) {
			addCriterion("S_ACCTCODE <>", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeGreaterThan(String value) {
			addCriterion("S_ACCTCODE >", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_ACCTCODE >=", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLessThan(String value) {
			addCriterion("S_ACCTCODE <", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLessThanOrEqualTo(String value) {
			addCriterion("S_ACCTCODE <=", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeLike(String value) {
			addCriterion("S_ACCTCODE like", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotLike(String value) {
			addCriterion("S_ACCTCODE not like", value, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeIn(List<String> values) {
			addCriterion("S_ACCTCODE in", values, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotIn(List<String> values) {
			addCriterion("S_ACCTCODE not in", values, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeBetween(String value1, String value2) {
			addCriterion("S_ACCTCODE between", value1, value2, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andSAcctcodeNotBetween(String value1, String value2) {
			addCriterion("S_ACCTCODE not between", value1, value2, "sAcctcode");
			return (Criteria) this;
		}

		public Criteria andIMercodeIsNull() {
			addCriterion("I_MERCODE is null");
			return (Criteria) this;
		}

		public Criteria andIMercodeIsNotNull() {
			addCriterion("I_MERCODE is not null");
			return (Criteria) this;
		}

		public Criteria andIMercodeEqualTo(Long value) {
			addCriterion("I_MERCODE =", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotEqualTo(Long value) {
			addCriterion("I_MERCODE <>", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThan(Long value) {
			addCriterion("I_MERCODE >", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE >=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThan(Long value) {
			addCriterion("I_MERCODE <", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE <=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeIn(List<Long> values) {
			addCriterion("I_MERCODE in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotIn(List<Long> values) {
			addCriterion("I_MERCODE not in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE not between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andSMernameIsNull() {
			addCriterion("S_MERNAME is null");
			return (Criteria) this;
		}

		public Criteria andSMernameIsNotNull() {
			addCriterion("S_MERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andSMernameEqualTo(String value) {
			addCriterion("S_MERNAME =", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotEqualTo(String value) {
			addCriterion("S_MERNAME <>", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameGreaterThan(String value) {
			addCriterion("S_MERNAME >", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERNAME >=", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLessThan(String value) {
			addCriterion("S_MERNAME <", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLessThanOrEqualTo(String value) {
			addCriterion("S_MERNAME <=", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLike(String value) {
			addCriterion("S_MERNAME like", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotLike(String value) {
			addCriterion("S_MERNAME not like", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameIn(List<String> values) {
			addCriterion("S_MERNAME in", values, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotIn(List<String> values) {
			addCriterion("S_MERNAME not in", values, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameBetween(String value1, String value2) {
			addCriterion("S_MERNAME between", value1, value2, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotBetween(String value1, String value2) {
			addCriterion("S_MERNAME not between", value1, value2, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrIsNull() {
			addCriterion("S_MERREGADDR is null");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrIsNotNull() {
			addCriterion("S_MERREGADDR is not null");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrEqualTo(String value) {
			addCriterion("S_MERREGADDR =", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrNotEqualTo(String value) {
			addCriterion("S_MERREGADDR <>", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrGreaterThan(String value) {
			addCriterion("S_MERREGADDR >", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERREGADDR >=", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrLessThan(String value) {
			addCriterion("S_MERREGADDR <", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrLessThanOrEqualTo(String value) {
			addCriterion("S_MERREGADDR <=", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrLike(String value) {
			addCriterion("S_MERREGADDR like", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrNotLike(String value) {
			addCriterion("S_MERREGADDR not like", value, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrIn(List<String> values) {
			addCriterion("S_MERREGADDR in", values, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrNotIn(List<String> values) {
			addCriterion("S_MERREGADDR not in", values, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrBetween(String value1, String value2) {
			addCriterion("S_MERREGADDR between", value1, value2, "sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSMerregaddrNotBetween(String value1, String value2) {
			addCriterion("S_MERREGADDR not between", value1, value2,
					"sMerregaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrIsNull() {
			addCriterion("S_BIZADDR is null");
			return (Criteria) this;
		}

		public Criteria andSBizaddrIsNotNull() {
			addCriterion("S_BIZADDR is not null");
			return (Criteria) this;
		}

		public Criteria andSBizaddrEqualTo(String value) {
			addCriterion("S_BIZADDR =", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrNotEqualTo(String value) {
			addCriterion("S_BIZADDR <>", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrGreaterThan(String value) {
			addCriterion("S_BIZADDR >", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrGreaterThanOrEqualTo(String value) {
			addCriterion("S_BIZADDR >=", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrLessThan(String value) {
			addCriterion("S_BIZADDR <", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrLessThanOrEqualTo(String value) {
			addCriterion("S_BIZADDR <=", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrLike(String value) {
			addCriterion("S_BIZADDR like", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrNotLike(String value) {
			addCriterion("S_BIZADDR not like", value, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrIn(List<String> values) {
			addCriterion("S_BIZADDR in", values, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrNotIn(List<String> values) {
			addCriterion("S_BIZADDR not in", values, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrBetween(String value1, String value2) {
			addCriterion("S_BIZADDR between", value1, value2, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSBizaddrNotBetween(String value1, String value2) {
			addCriterion("S_BIZADDR not between", value1, value2, "sBizaddr");
			return (Criteria) this;
		}

		public Criteria andSPasswdIsNull() {
			addCriterion("S_PASSWD is null");
			return (Criteria) this;
		}

		public Criteria andSPasswdIsNotNull() {
			addCriterion("S_PASSWD is not null");
			return (Criteria) this;
		}

		public Criteria andSPasswdEqualTo(String value) {
			addCriterion("S_PASSWD =", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdNotEqualTo(String value) {
			addCriterion("S_PASSWD <>", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdGreaterThan(String value) {
			addCriterion("S_PASSWD >", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdGreaterThanOrEqualTo(String value) {
			addCriterion("S_PASSWD >=", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdLessThan(String value) {
			addCriterion("S_PASSWD <", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdLessThanOrEqualTo(String value) {
			addCriterion("S_PASSWD <=", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdLike(String value) {
			addCriterion("S_PASSWD like", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdNotLike(String value) {
			addCriterion("S_PASSWD not like", value, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdIn(List<String> values) {
			addCriterion("S_PASSWD in", values, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdNotIn(List<String> values) {
			addCriterion("S_PASSWD not in", values, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdBetween(String value1, String value2) {
			addCriterion("S_PASSWD between", value1, value2, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSPasswdNotBetween(String value1, String value2) {
			addCriterion("S_PASSWD not between", value1, value2, "sPasswd");
			return (Criteria) this;
		}

		public Criteria andSDutyernameIsNull() {
			addCriterion("S_DUTYERNAME is null");
			return (Criteria) this;
		}

		public Criteria andSDutyernameIsNotNull() {
			addCriterion("S_DUTYERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andSDutyernameEqualTo(String value) {
			addCriterion("S_DUTYERNAME =", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameNotEqualTo(String value) {
			addCriterion("S_DUTYERNAME <>", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameGreaterThan(String value) {
			addCriterion("S_DUTYERNAME >", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameGreaterThanOrEqualTo(String value) {
			addCriterion("S_DUTYERNAME >=", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameLessThan(String value) {
			addCriterion("S_DUTYERNAME <", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameLessThanOrEqualTo(String value) {
			addCriterion("S_DUTYERNAME <=", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameLike(String value) {
			addCriterion("S_DUTYERNAME like", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameNotLike(String value) {
			addCriterion("S_DUTYERNAME not like", value, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameIn(List<String> values) {
			addCriterion("S_DUTYERNAME in", values, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameNotIn(List<String> values) {
			addCriterion("S_DUTYERNAME not in", values, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameBetween(String value1, String value2) {
			addCriterion("S_DUTYERNAME between", value1, value2, "sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyernameNotBetween(String value1, String value2) {
			addCriterion("S_DUTYERNAME not between", value1, value2,
					"sDutyername");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneIsNull() {
			addCriterion("S_DUTYERPHONE is null");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneIsNotNull() {
			addCriterion("S_DUTYERPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneEqualTo(String value) {
			addCriterion("S_DUTYERPHONE =", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneNotEqualTo(String value) {
			addCriterion("S_DUTYERPHONE <>", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneGreaterThan(String value) {
			addCriterion("S_DUTYERPHONE >", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneGreaterThanOrEqualTo(String value) {
			addCriterion("S_DUTYERPHONE >=", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneLessThan(String value) {
			addCriterion("S_DUTYERPHONE <", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneLessThanOrEqualTo(String value) {
			addCriterion("S_DUTYERPHONE <=", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneLike(String value) {
			addCriterion("S_DUTYERPHONE like", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneNotLike(String value) {
			addCriterion("S_DUTYERPHONE not like", value, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneIn(List<String> values) {
			addCriterion("S_DUTYERPHONE in", values, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneNotIn(List<String> values) {
			addCriterion("S_DUTYERPHONE not in", values, "sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneBetween(String value1, String value2) {
			addCriterion("S_DUTYERPHONE between", value1, value2,
					"sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSDutyerphoneNotBetween(String value1, String value2) {
			addCriterion("S_DUTYERPHONE not between", value1, value2,
					"sDutyerphone");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoIsNull() {
			addCriterion("S_MICROMSGNO is null");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoIsNotNull() {
			addCriterion("S_MICROMSGNO is not null");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoEqualTo(String value) {
			addCriterion("S_MICROMSGNO =", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoNotEqualTo(String value) {
			addCriterion("S_MICROMSGNO <>", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoGreaterThan(String value) {
			addCriterion("S_MICROMSGNO >", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoGreaterThanOrEqualTo(String value) {
			addCriterion("S_MICROMSGNO >=", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoLessThan(String value) {
			addCriterion("S_MICROMSGNO <", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoLessThanOrEqualTo(String value) {
			addCriterion("S_MICROMSGNO <=", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoLike(String value) {
			addCriterion("S_MICROMSGNO like", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoNotLike(String value) {
			addCriterion("S_MICROMSGNO not like", value, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoIn(List<String> values) {
			addCriterion("S_MICROMSGNO in", values, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoNotIn(List<String> values) {
			addCriterion("S_MICROMSGNO not in", values, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoBetween(String value1, String value2) {
			addCriterion("S_MICROMSGNO between", value1, value2, "sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSMicromsgnoNotBetween(String value1, String value2) {
			addCriterion("S_MICROMSGNO not between", value1, value2,
					"sMicromsgno");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusIsNull() {
			addCriterion("S_ACCTSTATUS is null");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusIsNotNull() {
			addCriterion("S_ACCTSTATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusEqualTo(String value) {
			addCriterion("S_ACCTSTATUS =", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusNotEqualTo(String value) {
			addCriterion("S_ACCTSTATUS <>", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusGreaterThan(String value) {
			addCriterion("S_ACCTSTATUS >", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusGreaterThanOrEqualTo(String value) {
			addCriterion("S_ACCTSTATUS >=", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusLessThan(String value) {
			addCriterion("S_ACCTSTATUS <", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusLessThanOrEqualTo(String value) {
			addCriterion("S_ACCTSTATUS <=", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusLike(String value) {
			addCriterion("S_ACCTSTATUS like", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusNotLike(String value) {
			addCriterion("S_ACCTSTATUS not like", value, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusIn(List<String> values) {
			addCriterion("S_ACCTSTATUS in", values, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusNotIn(List<String> values) {
			addCriterion("S_ACCTSTATUS not in", values, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusBetween(String value1, String value2) {
			addCriterion("S_ACCTSTATUS between", value1, value2, "sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andSAcctstatusNotBetween(String value1, String value2) {
			addCriterion("S_ACCTSTATUS not between", value1, value2,
					"sAcctstatus");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIsNull() {
			addCriterion("D_ACCTREGDATE is null");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIsNotNull() {
			addCriterion("D_ACCTREGDATE is not null");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE =", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE <>", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateGreaterThan(Date value) {
			addCriterion("D_ACCTREGDATE >", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateGreaterThanOrEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE >=", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateLessThan(Date value) {
			addCriterion("D_ACCTREGDATE <", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateLessThanOrEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE <=", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIn(List<Date> values) {
			addCriterion("D_ACCTREGDATE in", values, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotIn(List<Date> values) {
			addCriterion("D_ACCTREGDATE not in", values, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateBetween(Date value1, Date value2) {
			addCriterion("D_ACCTREGDATE between", value1, value2,
					"dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotBetween(Date value1, Date value2) {
			addCriterion("D_ACCTREGDATE not between", value1, value2,
					"dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgIsNull() {
			addCriterion("S_ACCTREGORG is null");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgIsNotNull() {
			addCriterion("S_ACCTREGORG is not null");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgEqualTo(String value) {
			addCriterion("S_ACCTREGORG =", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgNotEqualTo(String value) {
			addCriterion("S_ACCTREGORG <>", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgGreaterThan(String value) {
			addCriterion("S_ACCTREGORG >", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgGreaterThanOrEqualTo(String value) {
			addCriterion("S_ACCTREGORG >=", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgLessThan(String value) {
			addCriterion("S_ACCTREGORG <", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgLessThanOrEqualTo(String value) {
			addCriterion("S_ACCTREGORG <=", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgLike(String value) {
			addCriterion("S_ACCTREGORG like", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgNotLike(String value) {
			addCriterion("S_ACCTREGORG not like", value, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgIn(List<String> values) {
			addCriterion("S_ACCTREGORG in", values, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgNotIn(List<String> values) {
			addCriterion("S_ACCTREGORG not in", values, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgBetween(String value1, String value2) {
			addCriterion("S_ACCTREGORG between", value1, value2, "sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSAcctregorgNotBetween(String value1, String value2) {
			addCriterion("S_ACCTREGORG not between", value1, value2,
					"sAcctregorg");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeIsNull() {
			addCriterion("S_OFSERVORGCODE is null");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeIsNotNull() {
			addCriterion("S_OFSERVORGCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeEqualTo(String value) {
			addCriterion("S_OFSERVORGCODE =", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeNotEqualTo(String value) {
			addCriterion("S_OFSERVORGCODE <>", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeGreaterThan(String value) {
			addCriterion("S_OFSERVORGCODE >", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_OFSERVORGCODE >=", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeLessThan(String value) {
			addCriterion("S_OFSERVORGCODE <", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeLessThanOrEqualTo(String value) {
			addCriterion("S_OFSERVORGCODE <=", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeLike(String value) {
			addCriterion("S_OFSERVORGCODE like", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeNotLike(String value) {
			addCriterion("S_OFSERVORGCODE not like", value, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeIn(List<String> values) {
			addCriterion("S_OFSERVORGCODE in", values, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeNotIn(List<String> values) {
			addCriterion("S_OFSERVORGCODE not in", values, "sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeBetween(String value1, String value2) {
			addCriterion("S_OFSERVORGCODE between", value1, value2,
					"sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSOfservorgcodeNotBetween(String value1, String value2) {
			addCriterion("S_OFSERVORGCODE not between", value1, value2,
					"sOfservorgcode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIsNull() {
			addCriterion("S_UPPEMERCODE is null");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIsNotNull() {
			addCriterion("S_UPPEMERCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeEqualTo(String value) {
			addCriterion("S_UPPEMERCODE =", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotEqualTo(String value) {
			addCriterion("S_UPPEMERCODE <>", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeGreaterThan(String value) {
			addCriterion("S_UPPEMERCODE >", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_UPPEMERCODE >=", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLessThan(String value) {
			addCriterion("S_UPPEMERCODE <", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLessThanOrEqualTo(String value) {
			addCriterion("S_UPPEMERCODE <=", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLike(String value) {
			addCriterion("S_UPPEMERCODE like", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotLike(String value) {
			addCriterion("S_UPPEMERCODE not like", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIn(List<String> values) {
			addCriterion("S_UPPEMERCODE in", values, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotIn(List<String> values) {
			addCriterion("S_UPPEMERCODE not in", values, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeBetween(String value1, String value2) {
			addCriterion("S_UPPEMERCODE between", value1, value2,
					"sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotBetween(String value1, String value2) {
			addCriterion("S_UPPEMERCODE not between", value1, value2,
					"sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSBizclassIsNull() {
			addCriterion("S_BIZCLASS is null");
			return (Criteria) this;
		}

		public Criteria andSBizclassIsNotNull() {
			addCriterion("S_BIZCLASS is not null");
			return (Criteria) this;
		}

		public Criteria andSBizclassEqualTo(String value) {
			addCriterion("S_BIZCLASS =", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassNotEqualTo(String value) {
			addCriterion("S_BIZCLASS <>", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassGreaterThan(String value) {
			addCriterion("S_BIZCLASS >", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassGreaterThanOrEqualTo(String value) {
			addCriterion("S_BIZCLASS >=", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassLessThan(String value) {
			addCriterion("S_BIZCLASS <", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassLessThanOrEqualTo(String value) {
			addCriterion("S_BIZCLASS <=", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassLike(String value) {
			addCriterion("S_BIZCLASS like", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassNotLike(String value) {
			addCriterion("S_BIZCLASS not like", value, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassIn(List<String> values) {
			addCriterion("S_BIZCLASS in", values, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassNotIn(List<String> values) {
			addCriterion("S_BIZCLASS not in", values, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassBetween(String value1, String value2) {
			addCriterion("S_BIZCLASS between", value1, value2, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSBizclassNotBetween(String value1, String value2) {
			addCriterion("S_BIZCLASS not between", value1, value2, "sBizclass");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNull() {
			addCriterion("S_ISEFFECT is null");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNotNull() {
			addCriterion("S_ISEFFECT is not null");
			return (Criteria) this;
		}

		public Criteria andSIseffectEqualTo(String value) {
			addCriterion("S_ISEFFECT =", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotEqualTo(String value) {
			addCriterion("S_ISEFFECT <>", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThan(String value) {
			addCriterion("S_ISEFFECT >", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT >=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThan(String value) {
			addCriterion("S_ISEFFECT <", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT <=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLike(String value) {
			addCriterion("S_ISEFFECT like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotLike(String value) {
			addCriterion("S_ISEFFECT not like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectIn(List<String> values) {
			addCriterion("S_ISEFFECT in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotIn(List<String> values) {
			addCriterion("S_ISEFFECT not in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT not between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNull() {
			addCriterion("TS_SYSUPDATE is null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNotNull() {
			addCriterion("TS_SYSUPDATE is not null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE =", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <>", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThan(Date value) {
			addCriterion("TS_SYSUPDATE >", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE >=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThan(Date value) {
			addCriterion("TS_SYSUPDATE <", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE not in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE between", value1, value2, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE not between", value1, value2,
					"tsSysupdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERACCT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MERACCT
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 09:26:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}