package com.aisino.finace.account.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TmTerminfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public TmTerminfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIMercodeIsNull() {
			addCriterion("I_MERCODE is null");
			return (Criteria) this;
		}

		public Criteria andIMercodeIsNotNull() {
			addCriterion("I_MERCODE is not null");
			return (Criteria) this;
		}

		public Criteria andIMercodeEqualTo(Long value) {
			addCriterion("I_MERCODE =", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotEqualTo(Long value) {
			addCriterion("I_MERCODE <>", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThan(Long value) {
			addCriterion("I_MERCODE >", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE >=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThan(Long value) {
			addCriterion("I_MERCODE <", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE <=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeIn(List<Long> values) {
			addCriterion("I_MERCODE in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotIn(List<Long> values) {
			addCriterion("I_MERCODE not in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE not between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIsNull() {
			addCriterion("S_ORGUUID is null");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIsNotNull() {
			addCriterion("S_ORGUUID is not null");
			return (Criteria) this;
		}

		public Criteria andSOrguuidEqualTo(String value) {
			addCriterion("S_ORGUUID =", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotEqualTo(String value) {
			addCriterion("S_ORGUUID <>", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidGreaterThan(String value) {
			addCriterion("S_ORGUUID >", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidGreaterThanOrEqualTo(String value) {
			addCriterion("S_ORGUUID >=", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLessThan(String value) {
			addCriterion("S_ORGUUID <", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLessThanOrEqualTo(String value) {
			addCriterion("S_ORGUUID <=", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLike(String value) {
			addCriterion("S_ORGUUID like", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotLike(String value) {
			addCriterion("S_ORGUUID not like", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIn(List<String> values) {
			addCriterion("S_ORGUUID in", values, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotIn(List<String> values) {
			addCriterion("S_ORGUUID not in", values, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidBetween(String value1, String value2) {
			addCriterion("S_ORGUUID between", value1, value2, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotBetween(String value1, String value2) {
			addCriterion("S_ORGUUID not between", value1, value2, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSTermcodeIsNull() {
			addCriterion("S_TERMCODE is null");
			return (Criteria) this;
		}

		public Criteria andSTermcodeIsNotNull() {
			addCriterion("S_TERMCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSTermcodeEqualTo(String value) {
			addCriterion("S_TERMCODE =", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeNotEqualTo(String value) {
			addCriterion("S_TERMCODE <>", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeGreaterThan(String value) {
			addCriterion("S_TERMCODE >", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_TERMCODE >=", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeLessThan(String value) {
			addCriterion("S_TERMCODE <", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeLessThanOrEqualTo(String value) {
			addCriterion("S_TERMCODE <=", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeLike(String value) {
			addCriterion("S_TERMCODE like", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeNotLike(String value) {
			addCriterion("S_TERMCODE not like", value, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeIn(List<String> values) {
			addCriterion("S_TERMCODE in", values, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeNotIn(List<String> values) {
			addCriterion("S_TERMCODE not in", values, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeBetween(String value1, String value2) {
			addCriterion("S_TERMCODE between", value1, value2, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSTermcodeNotBetween(String value1, String value2) {
			addCriterion("S_TERMCODE not between", value1, value2, "sTermcode");
			return (Criteria) this;
		}

		public Criteria andSRemarkIsNull() {
			addCriterion("S_REMARK is null");
			return (Criteria) this;
		}

		public Criteria andSRemarkIsNotNull() {
			addCriterion("S_REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andSRemarkEqualTo(String value) {
			addCriterion("S_REMARK =", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotEqualTo(String value) {
			addCriterion("S_REMARK <>", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkGreaterThan(String value) {
			addCriterion("S_REMARK >", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("S_REMARK >=", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLessThan(String value) {
			addCriterion("S_REMARK <", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLessThanOrEqualTo(String value) {
			addCriterion("S_REMARK <=", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLike(String value) {
			addCriterion("S_REMARK like", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotLike(String value) {
			addCriterion("S_REMARK not like", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkIn(List<String> values) {
			addCriterion("S_REMARK in", values, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotIn(List<String> values) {
			addCriterion("S_REMARK not in", values, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkBetween(String value1, String value2) {
			addCriterion("S_REMARK between", value1, value2, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotBetween(String value1, String value2) {
			addCriterion("S_REMARK not between", value1, value2, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNull() {
			addCriterion("S_ISEFFECT is null");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNotNull() {
			addCriterion("S_ISEFFECT is not null");
			return (Criteria) this;
		}

		public Criteria andSIseffectEqualTo(String value) {
			addCriterion("S_ISEFFECT =", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotEqualTo(String value) {
			addCriterion("S_ISEFFECT <>", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThan(String value) {
			addCriterion("S_ISEFFECT >", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT >=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThan(String value) {
			addCriterion("S_ISEFFECT <", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT <=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLike(String value) {
			addCriterion("S_ISEFFECT like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotLike(String value) {
			addCriterion("S_ISEFFECT not like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectIn(List<String> values) {
			addCriterion("S_ISEFFECT in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotIn(List<String> values) {
			addCriterion("S_ISEFFECT not in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT not between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNull() {
			addCriterion("TS_SYSUPDATE is null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNotNull() {
			addCriterion("TS_SYSUPDATE is not null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE =", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <>", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThan(Date value) {
			addCriterion("TS_SYSUPDATE >", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE >=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThan(Date value) {
			addCriterion("TS_SYSUPDATE <", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE not in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE between", value1, value2, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE not between", value1, value2,
					"tsSysupdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_TERMINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_TERMINFO
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 09:26:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}