package com.aisino.finace.account.entity;

import java.util.Date;

public class MlApproveDealInfo extends MlApproveDealInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.CURR_STEP
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private String currStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.HANDLER
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private Long handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.START_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.END_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.DEAL_RESULT
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private String dealResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_approve_deal_info.DEAL_DESC
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    private String dealDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.CURR_STEP
     *
     * @return the value of ml_approve_deal_info.CURR_STEP
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public String getCurrStep() {
        return currStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.CURR_STEP
     *
     * @param currStep the value for ml_approve_deal_info.CURR_STEP
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setCurrStep(String currStep) {
        this.currStep = currStep == null ? null : currStep.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.HANDLER
     *
     * @return the value of ml_approve_deal_info.HANDLER
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public Long getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.HANDLER
     *
     * @param handler the value for ml_approve_deal_info.HANDLER
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setHandler(Long handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.START_TIME
     *
     * @return the value of ml_approve_deal_info.START_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.START_TIME
     *
     * @param startTime the value for ml_approve_deal_info.START_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.END_TIME
     *
     * @return the value of ml_approve_deal_info.END_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.END_TIME
     *
     * @param endTime the value for ml_approve_deal_info.END_TIME
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.DEAL_RESULT
     *
     * @return the value of ml_approve_deal_info.DEAL_RESULT
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public String getDealResult() {
        return dealResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.DEAL_RESULT
     *
     * @param dealResult the value for ml_approve_deal_info.DEAL_RESULT
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setDealResult(String dealResult) {
        this.dealResult = dealResult == null ? null : dealResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_approve_deal_info.DEAL_DESC
     *
     * @return the value of ml_approve_deal_info.DEAL_DESC
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public String getDealDesc() {
        return dealDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_approve_deal_info.DEAL_DESC
     *
     * @param dealDesc the value for ml_approve_deal_info.DEAL_DESC
     *
     * @mbggenerated Fri Aug 08 21:13:38 GMT+08:00 2014
     */
    public void setDealDesc(String dealDesc) {
        this.dealDesc = dealDesc == null ? null : dealDesc.trim();
    }
}