package com.aisino.finace.account.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MlOrgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public MlOrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrgNoIsNull() {
            addCriterion("ORG_NO is null");
            return (Criteria) this;
        }

        public Criteria andOrgNoIsNotNull() {
            addCriterion("ORG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNoEqualTo(String value) {
            addCriterion("ORG_NO =", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotEqualTo(String value) {
            addCriterion("ORG_NO <>", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoGreaterThan(String value) {
            addCriterion("ORG_NO >", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NO >=", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLessThan(String value) {
            addCriterion("ORG_NO <", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLessThanOrEqualTo(String value) {
            addCriterion("ORG_NO <=", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoLike(String value) {
            addCriterion("ORG_NO like", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotLike(String value) {
            addCriterion("ORG_NO not like", value, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoIn(List<String> values) {
            addCriterion("ORG_NO in", values, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotIn(List<String> values) {
            addCriterion("ORG_NO not in", values, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoBetween(String value1, String value2) {
            addCriterion("ORG_NO between", value1, value2, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNoNotBetween(String value1, String value2) {
            addCriterion("ORG_NO not between", value1, value2, "orgNo");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("ORG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("ORG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("ORG_NAME =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("ORG_NAME <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("ORG_NAME >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("ORG_NAME <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("ORG_NAME like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("ORG_NAME not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("ORG_NAME in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("ORG_NAME not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("ORG_NAME between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME not between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerIsNull() {
            addCriterion("ORG_OWNER is null");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerIsNotNull() {
            addCriterion("ORG_OWNER is not null");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerEqualTo(String value) {
            addCriterion("ORG_OWNER =", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerNotEqualTo(String value) {
            addCriterion("ORG_OWNER <>", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerGreaterThan(String value) {
            addCriterion("ORG_OWNER >", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_OWNER >=", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerLessThan(String value) {
            addCriterion("ORG_OWNER <", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerLessThanOrEqualTo(String value) {
            addCriterion("ORG_OWNER <=", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerLike(String value) {
            addCriterion("ORG_OWNER like", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerNotLike(String value) {
            addCriterion("ORG_OWNER not like", value, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerIn(List<String> values) {
            addCriterion("ORG_OWNER in", values, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerNotIn(List<String> values) {
            addCriterion("ORG_OWNER not in", values, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerBetween(String value1, String value2) {
            addCriterion("ORG_OWNER between", value1, value2, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgOwnerNotBetween(String value1, String value2) {
            addCriterion("ORG_OWNER not between", value1, value2, "orgOwner");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanIsNull() {
            addCriterion("ORG_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanIsNotNull() {
            addCriterion("ORG_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanEqualTo(String value) {
            addCriterion("ORG_LINKMAN =", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanNotEqualTo(String value) {
            addCriterion("ORG_LINKMAN <>", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanGreaterThan(String value) {
            addCriterion("ORG_LINKMAN >", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_LINKMAN >=", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanLessThan(String value) {
            addCriterion("ORG_LINKMAN <", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanLessThanOrEqualTo(String value) {
            addCriterion("ORG_LINKMAN <=", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanLike(String value) {
            addCriterion("ORG_LINKMAN like", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanNotLike(String value) {
            addCriterion("ORG_LINKMAN not like", value, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanIn(List<String> values) {
            addCriterion("ORG_LINKMAN in", values, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanNotIn(List<String> values) {
            addCriterion("ORG_LINKMAN not in", values, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanBetween(String value1, String value2) {
            addCriterion("ORG_LINKMAN between", value1, value2, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgLinkmanNotBetween(String value1, String value2) {
            addCriterion("ORG_LINKMAN not between", value1, value2, "orgLinkman");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneIsNull() {
            addCriterion("ORG_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneIsNotNull() {
            addCriterion("ORG_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneEqualTo(String value) {
            addCriterion("ORG_PHONE =", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneNotEqualTo(String value) {
            addCriterion("ORG_PHONE <>", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneGreaterThan(String value) {
            addCriterion("ORG_PHONE >", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_PHONE >=", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneLessThan(String value) {
            addCriterion("ORG_PHONE <", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneLessThanOrEqualTo(String value) {
            addCriterion("ORG_PHONE <=", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneLike(String value) {
            addCriterion("ORG_PHONE like", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneNotLike(String value) {
            addCriterion("ORG_PHONE not like", value, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneIn(List<String> values) {
            addCriterion("ORG_PHONE in", values, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneNotIn(List<String> values) {
            addCriterion("ORG_PHONE not in", values, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneBetween(String value1, String value2) {
            addCriterion("ORG_PHONE between", value1, value2, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andOrgPhoneNotBetween(String value1, String value2) {
            addCriterion("ORG_PHONE not between", value1, value2, "orgPhone");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("MODIFY_DATE is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("MODIFY_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(Date value) {
            addCriterion("MODIFY_DATE =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(Date value) {
            addCriterion("MODIFY_DATE <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(Date value) {
            addCriterion("MODIFY_DATE >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(Date value) {
            addCriterion("MODIFY_DATE <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_DATE <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<Date> values) {
            addCriterion("MODIFY_DATE in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<Date> values) {
            addCriterion("MODIFY_DATE not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_DATE not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andOperIsNull() {
            addCriterion("OPER is null");
            return (Criteria) this;
        }

        public Criteria andOperIsNotNull() {
            addCriterion("OPER is not null");
            return (Criteria) this;
        }

        public Criteria andOperEqualTo(Long value) {
            addCriterion("OPER =", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotEqualTo(Long value) {
            addCriterion("OPER <>", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperGreaterThan(Long value) {
            addCriterion("OPER >", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperGreaterThanOrEqualTo(Long value) {
            addCriterion("OPER >=", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperLessThan(Long value) {
            addCriterion("OPER <", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperLessThanOrEqualTo(Long value) {
            addCriterion("OPER <=", value, "oper");
            return (Criteria) this;
        }

        public Criteria andOperIn(List<Long> values) {
            addCriterion("OPER in", values, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotIn(List<Long> values) {
            addCriterion("OPER not in", values, "oper");
            return (Criteria) this;
        }

        public Criteria andOperBetween(Long value1, Long value2) {
            addCriterion("OPER between", value1, value2, "oper");
            return (Criteria) this;
        }

        public Criteria andOperNotBetween(Long value1, Long value2) {
            addCriterion("OPER not between", value1, value2, "oper");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ml_org
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ml_org
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}