package com.aisino.finace.account.entity;

public class MlRoleResc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role_resc.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_role_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long rescId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role_resc.ROLE_ID
     *
     * @return the value of ml_role_resc.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role_resc.ROLE_ID
     *
     * @param roleId the value for ml_role_resc.ROLE_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_role_resc.RESC_ID
     *
     * @return the value of ml_role_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_role_resc.RESC_ID
     *
     * @param rescId the value for ml_role_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescId(Long rescId) {
        this.rescId = rescId;
    }
}