package com.aisino.finace.account.entity;

public class MlSysResc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long rescId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_URL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_NAMESPACE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescNamespace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_MAIN_CLASS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescMainClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_TYPE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_ICON
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_JS_FILES
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescJsFiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.IS_LEAF
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private String rescStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_sys_resc.RESC_SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    private Integer rescSeq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_ID
     *
     * @return the value of ml_sys_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getRescId() {
        return rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_ID
     *
     * @param rescId the value for ml_sys_resc.RESC_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescId(Long rescId) {
        this.rescId = rescId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_NAME
     *
     * @return the value of ml_sys_resc.RESC_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescName() {
        return rescName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_NAME
     *
     * @param rescName the value for ml_sys_resc.RESC_NAME
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescName(String rescName) {
        this.rescName = rescName == null ? null : rescName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_DESC
     *
     * @return the value of ml_sys_resc.RESC_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescDesc() {
        return rescDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_DESC
     *
     * @param rescDesc the value for ml_sys_resc.RESC_DESC
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescDesc(String rescDesc) {
        this.rescDesc = rescDesc == null ? null : rescDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_URL
     *
     * @return the value of ml_sys_resc.RESC_URL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescUrl() {
        return rescUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_URL
     *
     * @param rescUrl the value for ml_sys_resc.RESC_URL
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescUrl(String rescUrl) {
        this.rescUrl = rescUrl == null ? null : rescUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_NAMESPACE
     *
     * @return the value of ml_sys_resc.RESC_NAMESPACE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescNamespace() {
        return rescNamespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_NAMESPACE
     *
     * @param rescNamespace the value for ml_sys_resc.RESC_NAMESPACE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescNamespace(String rescNamespace) {
        this.rescNamespace = rescNamespace == null ? null : rescNamespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_MAIN_CLASS
     *
     * @return the value of ml_sys_resc.RESC_MAIN_CLASS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescMainClass() {
        return rescMainClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_MAIN_CLASS
     *
     * @param rescMainClass the value for ml_sys_resc.RESC_MAIN_CLASS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescMainClass(String rescMainClass) {
        this.rescMainClass = rescMainClass == null ? null : rescMainClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_TYPE
     *
     * @return the value of ml_sys_resc.RESC_TYPE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescType() {
        return rescType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_TYPE
     *
     * @param rescType the value for ml_sys_resc.RESC_TYPE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescType(String rescType) {
        this.rescType = rescType == null ? null : rescType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_TITLE
     *
     * @return the value of ml_sys_resc.RESC_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescTitle() {
        return rescTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_TITLE
     *
     * @param rescTitle the value for ml_sys_resc.RESC_TITLE
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescTitle(String rescTitle) {
        this.rescTitle = rescTitle == null ? null : rescTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_ICON
     *
     * @return the value of ml_sys_resc.RESC_ICON
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescIcon() {
        return rescIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_ICON
     *
     * @param rescIcon the value for ml_sys_resc.RESC_ICON
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescIcon(String rescIcon) {
        this.rescIcon = rescIcon == null ? null : rescIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.PARENT_ID
     *
     * @return the value of ml_sys_resc.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.PARENT_ID
     *
     * @param parentId the value for ml_sys_resc.PARENT_ID
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_JS_FILES
     *
     * @return the value of ml_sys_resc.RESC_JS_FILES
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescJsFiles() {
        return rescJsFiles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_JS_FILES
     *
     * @param rescJsFiles the value for ml_sys_resc.RESC_JS_FILES
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescJsFiles(String rescJsFiles) {
        this.rescJsFiles = rescJsFiles == null ? null : rescJsFiles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.IS_LEAF
     *
     * @return the value of ml_sys_resc.IS_LEAF
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.IS_LEAF
     *
     * @param isLeaf the value for ml_sys_resc.IS_LEAF
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setIsLeaf(String isLeaf) {
        this.isLeaf = isLeaf == null ? null : isLeaf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_STATUS
     *
     * @return the value of ml_sys_resc.RESC_STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public String getRescStatus() {
        return rescStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_STATUS
     *
     * @param rescStatus the value for ml_sys_resc.RESC_STATUS
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescStatus(String rescStatus) {
        this.rescStatus = rescStatus == null ? null : rescStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_sys_resc.RESC_SEQ
     *
     * @return the value of ml_sys_resc.RESC_SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public Integer getRescSeq() {
        return rescSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_sys_resc.RESC_SEQ
     *
     * @param rescSeq the value for ml_sys_resc.RESC_SEQ
     *
     * @mbggenerated Sat Mar 29 20:40:29 GMT+08:00 2014
     */
    public void setRescSeq(Integer rescSeq) {
        this.rescSeq = rescSeq;
    }
}