package com.aisino.finace.account.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TmMerinfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public TmMerinfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIMercodeIsNull() {
			addCriterion("I_MERCODE is null");
			return (Criteria) this;
		}

		public Criteria andIMercodeIsNotNull() {
			addCriterion("I_MERCODE is not null");
			return (Criteria) this;
		}

		public Criteria andIMercodeEqualTo(Long value) {
			addCriterion("I_MERCODE =", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotEqualTo(Long value) {
			addCriterion("I_MERCODE <>", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThan(Long value) {
			addCriterion("I_MERCODE >", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeGreaterThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE >=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThan(Long value) {
			addCriterion("I_MERCODE <", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeLessThanOrEqualTo(Long value) {
			addCriterion("I_MERCODE <=", value, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeIn(List<Long> values) {
			addCriterion("I_MERCODE in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotIn(List<Long> values) {
			addCriterion("I_MERCODE not in", values, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andIMercodeNotBetween(Long value1, Long value2) {
			addCriterion("I_MERCODE not between", value1, value2, "iMercode");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIsNull() {
			addCriterion("S_ORGUUID is null");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIsNotNull() {
			addCriterion("S_ORGUUID is not null");
			return (Criteria) this;
		}

		public Criteria andSOrguuidEqualTo(String value) {
			addCriterion("S_ORGUUID =", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotEqualTo(String value) {
			addCriterion("S_ORGUUID <>", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidGreaterThan(String value) {
			addCriterion("S_ORGUUID >", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidGreaterThanOrEqualTo(String value) {
			addCriterion("S_ORGUUID >=", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLessThan(String value) {
			addCriterion("S_ORGUUID <", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLessThanOrEqualTo(String value) {
			addCriterion("S_ORGUUID <=", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidLike(String value) {
			addCriterion("S_ORGUUID like", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotLike(String value) {
			addCriterion("S_ORGUUID not like", value, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidIn(List<String> values) {
			addCriterion("S_ORGUUID in", values, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotIn(List<String> values) {
			addCriterion("S_ORGUUID not in", values, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidBetween(String value1, String value2) {
			addCriterion("S_ORGUUID between", value1, value2, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSOrguuidNotBetween(String value1, String value2) {
			addCriterion("S_ORGUUID not between", value1, value2, "sOrguuid");
			return (Criteria) this;
		}

		public Criteria andSMernameIsNull() {
			addCriterion("S_MERNAME is null");
			return (Criteria) this;
		}

		public Criteria andSMernameIsNotNull() {
			addCriterion("S_MERNAME is not null");
			return (Criteria) this;
		}

		public Criteria andSMernameEqualTo(String value) {
			addCriterion("S_MERNAME =", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotEqualTo(String value) {
			addCriterion("S_MERNAME <>", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameGreaterThan(String value) {
			addCriterion("S_MERNAME >", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERNAME >=", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLessThan(String value) {
			addCriterion("S_MERNAME <", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLessThanOrEqualTo(String value) {
			addCriterion("S_MERNAME <=", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameLike(String value) {
			addCriterion("S_MERNAME like", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotLike(String value) {
			addCriterion("S_MERNAME not like", value, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameIn(List<String> values) {
			addCriterion("S_MERNAME in", values, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotIn(List<String> values) {
			addCriterion("S_MERNAME not in", values, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameBetween(String value1, String value2) {
			addCriterion("S_MERNAME between", value1, value2, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMernameNotBetween(String value1, String value2) {
			addCriterion("S_MERNAME not between", value1, value2, "sMername");
			return (Criteria) this;
		}

		public Criteria andSMerstatusIsNull() {
			addCriterion("S_MERSTATUS is null");
			return (Criteria) this;
		}

		public Criteria andSMerstatusIsNotNull() {
			addCriterion("S_MERSTATUS is not null");
			return (Criteria) this;
		}

		public Criteria andSMerstatusEqualTo(String value) {
			addCriterion("S_MERSTATUS =", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusNotEqualTo(String value) {
			addCriterion("S_MERSTATUS <>", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusGreaterThan(String value) {
			addCriterion("S_MERSTATUS >", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERSTATUS >=", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusLessThan(String value) {
			addCriterion("S_MERSTATUS <", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusLessThanOrEqualTo(String value) {
			addCriterion("S_MERSTATUS <=", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusLike(String value) {
			addCriterion("S_MERSTATUS like", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusNotLike(String value) {
			addCriterion("S_MERSTATUS not like", value, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusIn(List<String> values) {
			addCriterion("S_MERSTATUS in", values, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusNotIn(List<String> values) {
			addCriterion("S_MERSTATUS not in", values, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusBetween(String value1, String value2) {
			addCriterion("S_MERSTATUS between", value1, value2, "sMerstatus");
			return (Criteria) this;
		}

		public Criteria andSMerstatusNotBetween(String value1, String value2) {
			addCriterion("S_MERSTATUS not between", value1, value2,
					"sMerstatus");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateIsNull() {
			addCriterion("D_MEREXPDATE is null");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateIsNotNull() {
			addCriterion("D_MEREXPDATE is not null");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateEqualTo(Date value) {
			addCriterion("D_MEREXPDATE =", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateNotEqualTo(Date value) {
			addCriterion("D_MEREXPDATE <>", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateGreaterThan(Date value) {
			addCriterion("D_MEREXPDATE >", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateGreaterThanOrEqualTo(Date value) {
			addCriterion("D_MEREXPDATE >=", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateLessThan(Date value) {
			addCriterion("D_MEREXPDATE <", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateLessThanOrEqualTo(Date value) {
			addCriterion("D_MEREXPDATE <=", value, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateIn(List<Date> values) {
			addCriterion("D_MEREXPDATE in", values, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateNotIn(List<Date> values) {
			addCriterion("D_MEREXPDATE not in", values, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateBetween(Date value1, Date value2) {
			addCriterion("D_MEREXPDATE between", value1, value2, "dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andDMerexpdateNotBetween(Date value1, Date value2) {
			addCriterion("D_MEREXPDATE not between", value1, value2,
					"dMerexpdate");
			return (Criteria) this;
		}

		public Criteria andSCitycodeIsNull() {
			addCriterion("S_CITYCODE is null");
			return (Criteria) this;
		}

		public Criteria andSCitycodeIsNotNull() {
			addCriterion("S_CITYCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSCitycodeEqualTo(String value) {
			addCriterion("S_CITYCODE =", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeNotEqualTo(String value) {
			addCriterion("S_CITYCODE <>", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeGreaterThan(String value) {
			addCriterion("S_CITYCODE >", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_CITYCODE >=", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeLessThan(String value) {
			addCriterion("S_CITYCODE <", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeLessThanOrEqualTo(String value) {
			addCriterion("S_CITYCODE <=", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeLike(String value) {
			addCriterion("S_CITYCODE like", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeNotLike(String value) {
			addCriterion("S_CITYCODE not like", value, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeIn(List<String> values) {
			addCriterion("S_CITYCODE in", values, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeNotIn(List<String> values) {
			addCriterion("S_CITYCODE not in", values, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeBetween(String value1, String value2) {
			addCriterion("S_CITYCODE between", value1, value2, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitycodeNotBetween(String value1, String value2) {
			addCriterion("S_CITYCODE not between", value1, value2, "sCitycode");
			return (Criteria) this;
		}

		public Criteria andSCitynameIsNull() {
			addCriterion("S_CITYNAME is null");
			return (Criteria) this;
		}

		public Criteria andSCitynameIsNotNull() {
			addCriterion("S_CITYNAME is not null");
			return (Criteria) this;
		}

		public Criteria andSCitynameEqualTo(String value) {
			addCriterion("S_CITYNAME =", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameNotEqualTo(String value) {
			addCriterion("S_CITYNAME <>", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameGreaterThan(String value) {
			addCriterion("S_CITYNAME >", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameGreaterThanOrEqualTo(String value) {
			addCriterion("S_CITYNAME >=", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameLessThan(String value) {
			addCriterion("S_CITYNAME <", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameLessThanOrEqualTo(String value) {
			addCriterion("S_CITYNAME <=", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameLike(String value) {
			addCriterion("S_CITYNAME like", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameNotLike(String value) {
			addCriterion("S_CITYNAME not like", value, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameIn(List<String> values) {
			addCriterion("S_CITYNAME in", values, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameNotIn(List<String> values) {
			addCriterion("S_CITYNAME not in", values, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameBetween(String value1, String value2) {
			addCriterion("S_CITYNAME between", value1, value2, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSCitynameNotBetween(String value1, String value2) {
			addCriterion("S_CITYNAME not between", value1, value2, "sCityname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameIsNull() {
			addCriterion("S_MERCONTNAME is null");
			return (Criteria) this;
		}

		public Criteria andSMercontnameIsNotNull() {
			addCriterion("S_MERCONTNAME is not null");
			return (Criteria) this;
		}

		public Criteria andSMercontnameEqualTo(String value) {
			addCriterion("S_MERCONTNAME =", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameNotEqualTo(String value) {
			addCriterion("S_MERCONTNAME <>", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameGreaterThan(String value) {
			addCriterion("S_MERCONTNAME >", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERCONTNAME >=", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameLessThan(String value) {
			addCriterion("S_MERCONTNAME <", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameLessThanOrEqualTo(String value) {
			addCriterion("S_MERCONTNAME <=", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameLike(String value) {
			addCriterion("S_MERCONTNAME like", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameNotLike(String value) {
			addCriterion("S_MERCONTNAME not like", value, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameIn(List<String> values) {
			addCriterion("S_MERCONTNAME in", values, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameNotIn(List<String> values) {
			addCriterion("S_MERCONTNAME not in", values, "sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameBetween(String value1, String value2) {
			addCriterion("S_MERCONTNAME between", value1, value2,
					"sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontnameNotBetween(String value1, String value2) {
			addCriterion("S_MERCONTNAME not between", value1, value2,
					"sMercontname");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneIsNull() {
			addCriterion("S_MERCONTPHONE is null");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneIsNotNull() {
			addCriterion("S_MERCONTPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneEqualTo(String value) {
			addCriterion("S_MERCONTPHONE =", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneNotEqualTo(String value) {
			addCriterion("S_MERCONTPHONE <>", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneGreaterThan(String value) {
			addCriterion("S_MERCONTPHONE >", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERCONTPHONE >=", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneLessThan(String value) {
			addCriterion("S_MERCONTPHONE <", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneLessThanOrEqualTo(String value) {
			addCriterion("S_MERCONTPHONE <=", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneLike(String value) {
			addCriterion("S_MERCONTPHONE like", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneNotLike(String value) {
			addCriterion("S_MERCONTPHONE not like", value, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneIn(List<String> values) {
			addCriterion("S_MERCONTPHONE in", values, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneNotIn(List<String> values) {
			addCriterion("S_MERCONTPHONE not in", values, "sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneBetween(String value1, String value2) {
			addCriterion("S_MERCONTPHONE between", value1, value2,
					"sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMercontphoneNotBetween(String value1, String value2) {
			addCriterion("S_MERCONTPHONE not between", value1, value2,
					"sMercontphone");
			return (Criteria) this;
		}

		public Criteria andSMeraddrIsNull() {
			addCriterion("S_MERADDR is null");
			return (Criteria) this;
		}

		public Criteria andSMeraddrIsNotNull() {
			addCriterion("S_MERADDR is not null");
			return (Criteria) this;
		}

		public Criteria andSMeraddrEqualTo(String value) {
			addCriterion("S_MERADDR =", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrNotEqualTo(String value) {
			addCriterion("S_MERADDR <>", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrGreaterThan(String value) {
			addCriterion("S_MERADDR >", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERADDR >=", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrLessThan(String value) {
			addCriterion("S_MERADDR <", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrLessThanOrEqualTo(String value) {
			addCriterion("S_MERADDR <=", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrLike(String value) {
			addCriterion("S_MERADDR like", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrNotLike(String value) {
			addCriterion("S_MERADDR not like", value, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrIn(List<String> values) {
			addCriterion("S_MERADDR in", values, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrNotIn(List<String> values) {
			addCriterion("S_MERADDR not in", values, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrBetween(String value1, String value2) {
			addCriterion("S_MERADDR between", value1, value2, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMeraddrNotBetween(String value1, String value2) {
			addCriterion("S_MERADDR not between", value1, value2, "sMeraddr");
			return (Criteria) this;
		}

		public Criteria andSMerzipIsNull() {
			addCriterion("S_MERZIP is null");
			return (Criteria) this;
		}

		public Criteria andSMerzipIsNotNull() {
			addCriterion("S_MERZIP is not null");
			return (Criteria) this;
		}

		public Criteria andSMerzipEqualTo(String value) {
			addCriterion("S_MERZIP =", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipNotEqualTo(String value) {
			addCriterion("S_MERZIP <>", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipGreaterThan(String value) {
			addCriterion("S_MERZIP >", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipGreaterThanOrEqualTo(String value) {
			addCriterion("S_MERZIP >=", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipLessThan(String value) {
			addCriterion("S_MERZIP <", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipLessThanOrEqualTo(String value) {
			addCriterion("S_MERZIP <=", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipLike(String value) {
			addCriterion("S_MERZIP like", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipNotLike(String value) {
			addCriterion("S_MERZIP not like", value, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipIn(List<String> values) {
			addCriterion("S_MERZIP in", values, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipNotIn(List<String> values) {
			addCriterion("S_MERZIP not in", values, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipBetween(String value1, String value2) {
			addCriterion("S_MERZIP between", value1, value2, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSMerzipNotBetween(String value1, String value2) {
			addCriterion("S_MERZIP not between", value1, value2, "sMerzip");
			return (Criteria) this;
		}

		public Criteria andSEmailIsNull() {
			addCriterion("S_EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andSEmailIsNotNull() {
			addCriterion("S_EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andSEmailEqualTo(String value) {
			addCriterion("S_EMAIL =", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailNotEqualTo(String value) {
			addCriterion("S_EMAIL <>", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailGreaterThan(String value) {
			addCriterion("S_EMAIL >", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailGreaterThanOrEqualTo(String value) {
			addCriterion("S_EMAIL >=", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailLessThan(String value) {
			addCriterion("S_EMAIL <", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailLessThanOrEqualTo(String value) {
			addCriterion("S_EMAIL <=", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailLike(String value) {
			addCriterion("S_EMAIL like", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailNotLike(String value) {
			addCriterion("S_EMAIL not like", value, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailIn(List<String> values) {
			addCriterion("S_EMAIL in", values, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailNotIn(List<String> values) {
			addCriterion("S_EMAIL not in", values, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailBetween(String value1, String value2) {
			addCriterion("S_EMAIL between", value1, value2, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSEmailNotBetween(String value1, String value2) {
			addCriterion("S_EMAIL not between", value1, value2, "sEmail");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIsNull() {
			addCriterion("S_UPPEMERCODE is null");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIsNotNull() {
			addCriterion("S_UPPEMERCODE is not null");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeEqualTo(String value) {
			addCriterion("S_UPPEMERCODE =", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotEqualTo(String value) {
			addCriterion("S_UPPEMERCODE <>", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeGreaterThan(String value) {
			addCriterion("S_UPPEMERCODE >", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeGreaterThanOrEqualTo(String value) {
			addCriterion("S_UPPEMERCODE >=", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLessThan(String value) {
			addCriterion("S_UPPEMERCODE <", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLessThanOrEqualTo(String value) {
			addCriterion("S_UPPEMERCODE <=", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeLike(String value) {
			addCriterion("S_UPPEMERCODE like", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotLike(String value) {
			addCriterion("S_UPPEMERCODE not like", value, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeIn(List<String> values) {
			addCriterion("S_UPPEMERCODE in", values, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotIn(List<String> values) {
			addCriterion("S_UPPEMERCODE not in", values, "sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeBetween(String value1, String value2) {
			addCriterion("S_UPPEMERCODE between", value1, value2,
					"sUppemercode");
			return (Criteria) this;
		}

		public Criteria andSUppemercodeNotBetween(String value1, String value2) {
			addCriterion("S_UPPEMERCODE not between", value1, value2,
					"sUppemercode");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIsNull() {
			addCriterion("D_ACCTREGDATE is null");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIsNotNull() {
			addCriterion("D_ACCTREGDATE is not null");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE =", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE <>", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateGreaterThan(Date value) {
			addCriterion("D_ACCTREGDATE >", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateGreaterThanOrEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE >=", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateLessThan(Date value) {
			addCriterion("D_ACCTREGDATE <", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateLessThanOrEqualTo(Date value) {
			addCriterion("D_ACCTREGDATE <=", value, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateIn(List<Date> values) {
			addCriterion("D_ACCTREGDATE in", values, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotIn(List<Date> values) {
			addCriterion("D_ACCTREGDATE not in", values, "dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateBetween(Date value1, Date value2) {
			addCriterion("D_ACCTREGDATE between", value1, value2,
					"dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andDAcctregdateNotBetween(Date value1, Date value2) {
			addCriterion("D_ACCTREGDATE not between", value1, value2,
					"dAcctregdate");
			return (Criteria) this;
		}

		public Criteria andSRemarkIsNull() {
			addCriterion("S_REMARK is null");
			return (Criteria) this;
		}

		public Criteria andSRemarkIsNotNull() {
			addCriterion("S_REMARK is not null");
			return (Criteria) this;
		}

		public Criteria andSRemarkEqualTo(String value) {
			addCriterion("S_REMARK =", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotEqualTo(String value) {
			addCriterion("S_REMARK <>", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkGreaterThan(String value) {
			addCriterion("S_REMARK >", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("S_REMARK >=", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLessThan(String value) {
			addCriterion("S_REMARK <", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLessThanOrEqualTo(String value) {
			addCriterion("S_REMARK <=", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkLike(String value) {
			addCriterion("S_REMARK like", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotLike(String value) {
			addCriterion("S_REMARK not like", value, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkIn(List<String> values) {
			addCriterion("S_REMARK in", values, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotIn(List<String> values) {
			addCriterion("S_REMARK not in", values, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkBetween(String value1, String value2) {
			addCriterion("S_REMARK between", value1, value2, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSRemarkNotBetween(String value1, String value2) {
			addCriterion("S_REMARK not between", value1, value2, "sRemark");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNull() {
			addCriterion("S_ISEFFECT is null");
			return (Criteria) this;
		}

		public Criteria andSIseffectIsNotNull() {
			addCriterion("S_ISEFFECT is not null");
			return (Criteria) this;
		}

		public Criteria andSIseffectEqualTo(String value) {
			addCriterion("S_ISEFFECT =", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotEqualTo(String value) {
			addCriterion("S_ISEFFECT <>", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThan(String value) {
			addCriterion("S_ISEFFECT >", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectGreaterThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT >=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThan(String value) {
			addCriterion("S_ISEFFECT <", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLessThanOrEqualTo(String value) {
			addCriterion("S_ISEFFECT <=", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectLike(String value) {
			addCriterion("S_ISEFFECT like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotLike(String value) {
			addCriterion("S_ISEFFECT not like", value, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectIn(List<String> values) {
			addCriterion("S_ISEFFECT in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotIn(List<String> values) {
			addCriterion("S_ISEFFECT not in", values, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andSIseffectNotBetween(String value1, String value2) {
			addCriterion("S_ISEFFECT not between", value1, value2, "sIseffect");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNull() {
			addCriterion("TS_SYSUPDATE is null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIsNotNull() {
			addCriterion("TS_SYSUPDATE is not null");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE =", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <>", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThan(Date value) {
			addCriterion("TS_SYSUPDATE >", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateGreaterThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE >=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThan(Date value) {
			addCriterion("TS_SYSUPDATE <", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateLessThanOrEqualTo(Date value) {
			addCriterion("TS_SYSUPDATE <=", value, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotIn(List<Date> values) {
			addCriterion("TS_SYSUPDATE not in", values, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE between", value1, value2, "tsSysupdate");
			return (Criteria) this;
		}

		public Criteria andTsSysupdateNotBetween(Date value1, Date value2) {
			addCriterion("TS_SYSUPDATE not between", value1, value2,
					"tsSysupdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TM_MERINFO
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TM_MERINFO
     *
     * @mbggenerated do_not_delete_during_merge Mon May 18 09:26:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}