package com.aisino.finace.account.entity;

import java.util.Date;

public class TmMsinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsuuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sOrguuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Long iMercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_CITYCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sCitycode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_CITYNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sCityname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSZIP
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMszip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSMANAGERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsmanagername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_MSMANAGERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sMsmanagerphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sIseffect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_MSINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date tsSysupdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSUUID
	 * @return  the value of TM_MSINFO.S_MSUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsuuid() {
		return sMsuuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSUUID
	 * @param sMsuuid  the value for TM_MSINFO.S_MSUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsuuid(String sMsuuid) {
		this.sMsuuid = sMsuuid == null ? null : sMsuuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_ORGUUID
	 * @return  the value of TM_MSINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsOrguuid() {
		return sOrguuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_ORGUUID
	 * @param sOrguuid  the value for TM_MSINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsOrguuid(String sOrguuid) {
		this.sOrguuid = sOrguuid == null ? null : sOrguuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.I_MERCODE
	 * @return  the value of TM_MSINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Long getiMercode() {
		return iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.I_MERCODE
	 * @param iMercode  the value for TM_MSINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setiMercode(Long iMercode) {
		this.iMercode = iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSNAME
	 * @return  the value of TM_MSINFO.S_MSNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsname() {
		return sMsname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSNAME
	 * @param sMsname  the value for TM_MSINFO.S_MSNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsname(String sMsname) {
		this.sMsname = sMsname == null ? null : sMsname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSSTATUS
	 * @return  the value of TM_MSINFO.S_MSSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsstatus() {
		return sMsstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSSTATUS
	 * @param sMsstatus  the value for TM_MSINFO.S_MSSTATUS
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsstatus(String sMsstatus) {
		this.sMsstatus = sMsstatus == null ? null : sMsstatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_CITYCODE
	 * @return  the value of TM_MSINFO.S_CITYCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsCitycode() {
		return sCitycode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_CITYCODE
	 * @param sCitycode  the value for TM_MSINFO.S_CITYCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsCitycode(String sCitycode) {
		this.sCitycode = sCitycode == null ? null : sCitycode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_CITYNAME
	 * @return  the value of TM_MSINFO.S_CITYNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsCityname() {
		return sCityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_CITYNAME
	 * @param sCityname  the value for TM_MSINFO.S_CITYNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsCityname(String sCityname) {
		this.sCityname = sCityname == null ? null : sCityname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSADDR
	 * @return  the value of TM_MSINFO.S_MSADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsaddr() {
		return sMsaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSADDR
	 * @param sMsaddr  the value for TM_MSINFO.S_MSADDR
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsaddr(String sMsaddr) {
		this.sMsaddr = sMsaddr == null ? null : sMsaddr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSZIP
	 * @return  the value of TM_MSINFO.S_MSZIP
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMszip() {
		return sMszip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSZIP
	 * @param sMszip  the value for TM_MSINFO.S_MSZIP
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMszip(String sMszip) {
		this.sMszip = sMszip == null ? null : sMszip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSMANAGERNAME
	 * @return  the value of TM_MSINFO.S_MSMANAGERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsmanagername() {
		return sMsmanagername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSMANAGERNAME
	 * @param sMsmanagername  the value for TM_MSINFO.S_MSMANAGERNAME
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsmanagername(String sMsmanagername) {
		this.sMsmanagername = sMsmanagername == null ? null : sMsmanagername
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_MSMANAGERPHONE
	 * @return  the value of TM_MSINFO.S_MSMANAGERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsMsmanagerphone() {
		return sMsmanagerphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_MSMANAGERPHONE
	 * @param sMsmanagerphone  the value for TM_MSINFO.S_MSMANAGERPHONE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsMsmanagerphone(String sMsmanagerphone) {
		this.sMsmanagerphone = sMsmanagerphone == null ? null : sMsmanagerphone
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_EMAIL
	 * @return  the value of TM_MSINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsEmail() {
		return sEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_EMAIL
	 * @param sEmail  the value for TM_MSINFO.S_EMAIL
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsEmail(String sEmail) {
		this.sEmail = sEmail == null ? null : sEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_REMARK
	 * @return  the value of TM_MSINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsRemark() {
		return sRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_REMARK
	 * @param sRemark  the value for TM_MSINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsRemark(String sRemark) {
		this.sRemark = sRemark == null ? null : sRemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.S_ISEFFECT
	 * @return  the value of TM_MSINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsIseffect() {
		return sIseffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.S_ISEFFECT
	 * @param sIseffect  the value for TM_MSINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsIseffect(String sIseffect) {
		this.sIseffect = sIseffect == null ? null : sIseffect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_MSINFO.TS_SYSUPDATE
	 * @return  the value of TM_MSINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getTsSysupdate() {
		return tsSysupdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_MSINFO.TS_SYSUPDATE
	 * @param tsSysupdate  the value for TM_MSINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setTsSysupdate(Date tsSysupdate) {
		this.tsSysupdate = tsSysupdate;
	}
}