package com.aisino.finace.account.entity;

import java.util.Date;

public class TmTerminfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Long iMercode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sOrguuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.S_TERMCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sTermcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private String sIseffect;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TM_TERMINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	private Date tsSysupdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.I_MERCODE
	 * @return  the value of TM_TERMINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Long getiMercode() {
		return iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.I_MERCODE
	 * @param iMercode  the value for TM_TERMINFO.I_MERCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setiMercode(Long iMercode) {
		this.iMercode = iMercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.S_ORGUUID
	 * @return  the value of TM_TERMINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsOrguuid() {
		return sOrguuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.S_ORGUUID
	 * @param sOrguuid  the value for TM_TERMINFO.S_ORGUUID
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsOrguuid(String sOrguuid) {
		this.sOrguuid = sOrguuid == null ? null : sOrguuid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.S_TERMCODE
	 * @return  the value of TM_TERMINFO.S_TERMCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsTermcode() {
		return sTermcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.S_TERMCODE
	 * @param sTermcode  the value for TM_TERMINFO.S_TERMCODE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsTermcode(String sTermcode) {
		this.sTermcode = sTermcode == null ? null : sTermcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.S_REMARK
	 * @return  the value of TM_TERMINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsRemark() {
		return sRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.S_REMARK
	 * @param sRemark  the value for TM_TERMINFO.S_REMARK
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsRemark(String sRemark) {
		this.sRemark = sRemark == null ? null : sRemark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.S_ISEFFECT
	 * @return  the value of TM_TERMINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public String getsIseffect() {
		return sIseffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.S_ISEFFECT
	 * @param sIseffect  the value for TM_TERMINFO.S_ISEFFECT
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setsIseffect(String sIseffect) {
		this.sIseffect = sIseffect == null ? null : sIseffect.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TM_TERMINFO.TS_SYSUPDATE
	 * @return  the value of TM_TERMINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public Date getTsSysupdate() {
		return tsSysupdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TM_TERMINFO.TS_SYSUPDATE
	 * @param tsSysupdate  the value for TM_TERMINFO.TS_SYSUPDATE
	 * @mbggenerated  Thu May 21 17:25:15 CST 2015
	 */
	public void setTsSysupdate(Date tsSysupdate) {
		this.tsSysupdate = tsSysupdate;
	}
}