package com.aisino.finace.account.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TvTradetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public TvTradetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSTrasrlnoIsNull() {
            addCriterion("S_TRASRLNO is null");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoIsNotNull() {
            addCriterion("S_TRASRLNO is not null");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoEqualTo(BigDecimal value) {
            addCriterion("S_TRASRLNO =", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoNotEqualTo(BigDecimal value) {
            addCriterion("S_TRASRLNO <>", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoGreaterThan(BigDecimal value) {
            addCriterion("S_TRASRLNO >", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("S_TRASRLNO >=", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoLessThan(BigDecimal value) {
            addCriterion("S_TRASRLNO <", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("S_TRASRLNO <=", value, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoIn(List<BigDecimal> values) {
            addCriterion("S_TRASRLNO in", values, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoNotIn(List<BigDecimal> values) {
            addCriterion("S_TRASRLNO not in", values, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_TRASRLNO between", value1, value2, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSTrasrlnoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("S_TRASRLNO not between", value1, value2, "sTrasrlno");
            return (Criteria) this;
        }

        public Criteria andSConntypeIsNull() {
            addCriterion("S_CONNTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSConntypeIsNotNull() {
            addCriterion("S_CONNTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSConntypeEqualTo(String value) {
            addCriterion("S_CONNTYPE =", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeNotEqualTo(String value) {
            addCriterion("S_CONNTYPE <>", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeGreaterThan(String value) {
            addCriterion("S_CONNTYPE >", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeGreaterThanOrEqualTo(String value) {
            addCriterion("S_CONNTYPE >=", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeLessThan(String value) {
            addCriterion("S_CONNTYPE <", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeLessThanOrEqualTo(String value) {
            addCriterion("S_CONNTYPE <=", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeLike(String value) {
            addCriterion("S_CONNTYPE like", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeNotLike(String value) {
            addCriterion("S_CONNTYPE not like", value, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeIn(List<String> values) {
            addCriterion("S_CONNTYPE in", values, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeNotIn(List<String> values) {
            addCriterion("S_CONNTYPE not in", values, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeBetween(String value1, String value2) {
            addCriterion("S_CONNTYPE between", value1, value2, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSConntypeNotBetween(String value1, String value2) {
            addCriterion("S_CONNTYPE not between", value1, value2, "sConntype");
            return (Criteria) this;
        }

        public Criteria andSMeracctIsNull() {
            addCriterion("S_MERACCT is null");
            return (Criteria) this;
        }

        public Criteria andSMeracctIsNotNull() {
            addCriterion("S_MERACCT is not null");
            return (Criteria) this;
        }

        public Criteria andSMeracctEqualTo(String value) {
            addCriterion("S_MERACCT =", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctNotEqualTo(String value) {
            addCriterion("S_MERACCT <>", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctGreaterThan(String value) {
            addCriterion("S_MERACCT >", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctGreaterThanOrEqualTo(String value) {
            addCriterion("S_MERACCT >=", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctLessThan(String value) {
            addCriterion("S_MERACCT <", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctLessThanOrEqualTo(String value) {
            addCriterion("S_MERACCT <=", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctLike(String value) {
            addCriterion("S_MERACCT like", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctNotLike(String value) {
            addCriterion("S_MERACCT not like", value, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctIn(List<String> values) {
            addCriterion("S_MERACCT in", values, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctNotIn(List<String> values) {
            addCriterion("S_MERACCT not in", values, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctBetween(String value1, String value2) {
            addCriterion("S_MERACCT between", value1, value2, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSMeracctNotBetween(String value1, String value2) {
            addCriterion("S_MERACCT not between", value1, value2, "sMeracct");
            return (Criteria) this;
        }

        public Criteria andSTermcodeIsNull() {
            addCriterion("S_TERMCODE is null");
            return (Criteria) this;
        }

        public Criteria andSTermcodeIsNotNull() {
            addCriterion("S_TERMCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSTermcodeEqualTo(String value) {
            addCriterion("S_TERMCODE =", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeNotEqualTo(String value) {
            addCriterion("S_TERMCODE <>", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeGreaterThan(String value) {
            addCriterion("S_TERMCODE >", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeGreaterThanOrEqualTo(String value) {
            addCriterion("S_TERMCODE >=", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeLessThan(String value) {
            addCriterion("S_TERMCODE <", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeLessThanOrEqualTo(String value) {
            addCriterion("S_TERMCODE <=", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeLike(String value) {
            addCriterion("S_TERMCODE like", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeNotLike(String value) {
            addCriterion("S_TERMCODE not like", value, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeIn(List<String> values) {
            addCriterion("S_TERMCODE in", values, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeNotIn(List<String> values) {
            addCriterion("S_TERMCODE not in", values, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeBetween(String value1, String value2) {
            addCriterion("S_TERMCODE between", value1, value2, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTermcodeNotBetween(String value1, String value2) {
            addCriterion("S_TERMCODE not between", value1, value2, "sTermcode");
            return (Criteria) this;
        }

        public Criteria andSTranstypeIsNull() {
            addCriterion("S_TRANSTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSTranstypeIsNotNull() {
            addCriterion("S_TRANSTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSTranstypeEqualTo(String value) {
            addCriterion("S_TRANSTYPE =", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeNotEqualTo(String value) {
            addCriterion("S_TRANSTYPE <>", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeGreaterThan(String value) {
            addCriterion("S_TRANSTYPE >", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeGreaterThanOrEqualTo(String value) {
            addCriterion("S_TRANSTYPE >=", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeLessThan(String value) {
            addCriterion("S_TRANSTYPE <", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeLessThanOrEqualTo(String value) {
            addCriterion("S_TRANSTYPE <=", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeLike(String value) {
            addCriterion("S_TRANSTYPE like", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeNotLike(String value) {
            addCriterion("S_TRANSTYPE not like", value, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeIn(List<String> values) {
            addCriterion("S_TRANSTYPE in", values, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeNotIn(List<String> values) {
            addCriterion("S_TRANSTYPE not in", values, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeBetween(String value1, String value2) {
            addCriterion("S_TRANSTYPE between", value1, value2, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSTranstypeNotBetween(String value1, String value2) {
            addCriterion("S_TRANSTYPE not between", value1, value2, "sTranstype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeIsNull() {
            addCriterion("S_CARDIOTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeIsNotNull() {
            addCriterion("S_CARDIOTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeEqualTo(String value) {
            addCriterion("S_CARDIOTYPE =", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeNotEqualTo(String value) {
            addCriterion("S_CARDIOTYPE <>", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeGreaterThan(String value) {
            addCriterion("S_CARDIOTYPE >", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeGreaterThanOrEqualTo(String value) {
            addCriterion("S_CARDIOTYPE >=", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeLessThan(String value) {
            addCriterion("S_CARDIOTYPE <", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeLessThanOrEqualTo(String value) {
            addCriterion("S_CARDIOTYPE <=", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeLike(String value) {
            addCriterion("S_CARDIOTYPE like", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeNotLike(String value) {
            addCriterion("S_CARDIOTYPE not like", value, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeIn(List<String> values) {
            addCriterion("S_CARDIOTYPE in", values, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeNotIn(List<String> values) {
            addCriterion("S_CARDIOTYPE not in", values, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeBetween(String value1, String value2) {
            addCriterion("S_CARDIOTYPE between", value1, value2, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andSCardiotypeNotBetween(String value1, String value2) {
            addCriterion("S_CARDIOTYPE not between", value1, value2, "sCardiotype");
            return (Criteria) this;
        }

        public Criteria andDTransdateIsNull() {
            addCriterion("D_TRANSDATE is null");
            return (Criteria) this;
        }

        public Criteria andDTransdateIsNotNull() {
            addCriterion("D_TRANSDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDTransdateEqualTo(Date value) {
            addCriterion("D_TRANSDATE =", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateNotEqualTo(Date value) {
            addCriterion("D_TRANSDATE <>", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateGreaterThan(Date value) {
            addCriterion("D_TRANSDATE >", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateGreaterThanOrEqualTo(Date value) {
            addCriterion("D_TRANSDATE >=", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateLessThan(Date value) {
            addCriterion("D_TRANSDATE <", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateLessThanOrEqualTo(Date value) {
            addCriterion("D_TRANSDATE <=", value, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateIn(List<Date> values) {
            addCriterion("D_TRANSDATE in", values, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateNotIn(List<Date> values) {
            addCriterion("D_TRANSDATE not in", values, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateBetween(Date value1, Date value2) {
            addCriterion("D_TRANSDATE between", value1, value2, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDTransdateNotBetween(Date value1, Date value2) {
            addCriterion("D_TRANSDATE not between", value1, value2, "dTransdate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateIsNull() {
            addCriterion("D_BALANCEDATE is null");
            return (Criteria) this;
        }

        public Criteria andDBalancedateIsNotNull() {
            addCriterion("D_BALANCEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDBalancedateEqualTo(Date value) {
            addCriterion("D_BALANCEDATE =", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateNotEqualTo(Date value) {
            addCriterion("D_BALANCEDATE <>", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateGreaterThan(Date value) {
            addCriterion("D_BALANCEDATE >", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateGreaterThanOrEqualTo(Date value) {
            addCriterion("D_BALANCEDATE >=", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateLessThan(Date value) {
            addCriterion("D_BALANCEDATE <", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateLessThanOrEqualTo(Date value) {
            addCriterion("D_BALANCEDATE <=", value, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateIn(List<Date> values) {
            addCriterion("D_BALANCEDATE in", values, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateNotIn(List<Date> values) {
            addCriterion("D_BALANCEDATE not in", values, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateBetween(Date value1, Date value2) {
            addCriterion("D_BALANCEDATE between", value1, value2, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andDBalancedateNotBetween(Date value1, Date value2) {
            addCriterion("D_BALANCEDATE not between", value1, value2, "dBalancedate");
            return (Criteria) this;
        }

        public Criteria andFTransamtIsNull() {
            addCriterion("F_TRANSAMT is null");
            return (Criteria) this;
        }

        public Criteria andFTransamtIsNotNull() {
            addCriterion("F_TRANSAMT is not null");
            return (Criteria) this;
        }

        public Criteria andFTransamtEqualTo(BigDecimal value) {
            addCriterion("F_TRANSAMT =", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtNotEqualTo(BigDecimal value) {
            addCriterion("F_TRANSAMT <>", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtGreaterThan(BigDecimal value) {
            addCriterion("F_TRANSAMT >", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_TRANSAMT >=", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtLessThan(BigDecimal value) {
            addCriterion("F_TRANSAMT <", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_TRANSAMT <=", value, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtIn(List<BigDecimal> values) {
            addCriterion("F_TRANSAMT in", values, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtNotIn(List<BigDecimal> values) {
            addCriterion("F_TRANSAMT not in", values, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_TRANSAMT between", value1, value2, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andFTransamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_TRANSAMT not between", value1, value2, "fTransamt");
            return (Criteria) this;
        }

        public Criteria andSMccIsNull() {
            addCriterion("S_MCC is null");
            return (Criteria) this;
        }

        public Criteria andSMccIsNotNull() {
            addCriterion("S_MCC is not null");
            return (Criteria) this;
        }

        public Criteria andSMccEqualTo(String value) {
            addCriterion("S_MCC =", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccNotEqualTo(String value) {
            addCriterion("S_MCC <>", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccGreaterThan(String value) {
            addCriterion("S_MCC >", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccGreaterThanOrEqualTo(String value) {
            addCriterion("S_MCC >=", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccLessThan(String value) {
            addCriterion("S_MCC <", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccLessThanOrEqualTo(String value) {
            addCriterion("S_MCC <=", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccLike(String value) {
            addCriterion("S_MCC like", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccNotLike(String value) {
            addCriterion("S_MCC not like", value, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccIn(List<String> values) {
            addCriterion("S_MCC in", values, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccNotIn(List<String> values) {
            addCriterion("S_MCC not in", values, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccBetween(String value1, String value2) {
            addCriterion("S_MCC between", value1, value2, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSMccNotBetween(String value1, String value2) {
            addCriterion("S_MCC not between", value1, value2, "sMcc");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeIsNull() {
            addCriterion("S_HANDLCHARGDCTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeIsNotNull() {
            addCriterion("S_HANDLCHARGDCTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeEqualTo(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE =", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeNotEqualTo(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE <>", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeGreaterThan(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE >", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeGreaterThanOrEqualTo(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE >=", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeLessThan(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE <", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeLessThanOrEqualTo(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE <=", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeLike(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE like", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeNotLike(String value) {
            addCriterion("S_HANDLCHARGDCTTYPE not like", value, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeIn(List<String> values) {
            addCriterion("S_HANDLCHARGDCTTYPE in", values, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeNotIn(List<String> values) {
            addCriterion("S_HANDLCHARGDCTTYPE not in", values, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeBetween(String value1, String value2) {
            addCriterion("S_HANDLCHARGDCTTYPE between", value1, value2, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andSHandlchargdcttypeNotBetween(String value1, String value2) {
            addCriterion("S_HANDLCHARGDCTTYPE not between", value1, value2, "sHandlchargdcttype");
            return (Criteria) this;
        }

        public Criteria andFFeeratioIsNull() {
            addCriterion("F_FEERATIO is null");
            return (Criteria) this;
        }

        public Criteria andFFeeratioIsNotNull() {
            addCriterion("F_FEERATIO is not null");
            return (Criteria) this;
        }

        public Criteria andFFeeratioEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIO =", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioNotEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIO <>", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioGreaterThan(BigDecimal value) {
            addCriterion("F_FEERATIO >", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIO >=", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioLessThan(BigDecimal value) {
            addCriterion("F_FEERATIO <", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIO <=", value, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioIn(List<BigDecimal> values) {
            addCriterion("F_FEERATIO in", values, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioNotIn(List<BigDecimal> values) {
            addCriterion("F_FEERATIO not in", values, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_FEERATIO between", value1, value2, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_FEERATIO not between", value1, value2, "fFeeratio");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtIsNull() {
            addCriterion("F_FEERATIOAMT is null");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtIsNotNull() {
            addCriterion("F_FEERATIOAMT is not null");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIOAMT =", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtNotEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIOAMT <>", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtGreaterThan(BigDecimal value) {
            addCriterion("F_FEERATIOAMT >", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIOAMT >=", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtLessThan(BigDecimal value) {
            addCriterion("F_FEERATIOAMT <", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_FEERATIOAMT <=", value, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtIn(List<BigDecimal> values) {
            addCriterion("F_FEERATIOAMT in", values, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtNotIn(List<BigDecimal> values) {
            addCriterion("F_FEERATIOAMT not in", values, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_FEERATIOAMT between", value1, value2, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFFeeratioamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_FEERATIOAMT not between", value1, value2, "fFeeratioamt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtIsNull() {
            addCriterion("F_HANDLCHARGRATIOULMT is null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtIsNotNull() {
            addCriterion("F_HANDLCHARGRATIOULMT is not null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT =", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtNotEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT <>", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtGreaterThan(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT >", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT >=", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtLessThan(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT <", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOULMT <=", value, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARGRATIOULMT in", values, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtNotIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARGRATIOULMT not in", values, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARGRATIOULMT between", value1, value2, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratioulmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARGRATIOULMT not between", value1, value2, "fHandlchargratioulmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtIsNull() {
            addCriterion("F_HANDLCHARGRATIOLLMT is null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtIsNotNull() {
            addCriterion("F_HANDLCHARGRATIOLLMT is not null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT =", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtNotEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT <>", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtGreaterThan(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT >", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT >=", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtLessThan(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT <", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARGRATIOLLMT <=", value, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARGRATIOLLMT in", values, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtNotIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARGRATIOLLMT not in", values, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARGRATIOLLMT between", value1, value2, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargratiollmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARGRATIOLLMT not between", value1, value2, "fHandlchargratiollmt");
            return (Criteria) this;
        }

        public Criteria andFHandlchargIsNull() {
            addCriterion("F_HANDLCHARG is null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargIsNotNull() {
            addCriterion("F_HANDLCHARG is not null");
            return (Criteria) this;
        }

        public Criteria andFHandlchargEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARG =", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargNotEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARG <>", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargGreaterThan(BigDecimal value) {
            addCriterion("F_HANDLCHARG >", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARG >=", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargLessThan(BigDecimal value) {
            addCriterion("F_HANDLCHARG <", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_HANDLCHARG <=", value, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARG in", values, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargNotIn(List<BigDecimal> values) {
            addCriterion("F_HANDLCHARG not in", values, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARG between", value1, value2, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFHandlchargNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_HANDLCHARG not between", value1, value2, "fHandlcharg");
            return (Criteria) this;
        }

        public Criteria andFActualamtIsNull() {
            addCriterion("F_ACTUALAMT is null");
            return (Criteria) this;
        }

        public Criteria andFActualamtIsNotNull() {
            addCriterion("F_ACTUALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andFActualamtEqualTo(BigDecimal value) {
            addCriterion("F_ACTUALAMT =", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtNotEqualTo(BigDecimal value) {
            addCriterion("F_ACTUALAMT <>", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtGreaterThan(BigDecimal value) {
            addCriterion("F_ACTUALAMT >", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("F_ACTUALAMT >=", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtLessThan(BigDecimal value) {
            addCriterion("F_ACTUALAMT <", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("F_ACTUALAMT <=", value, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtIn(List<BigDecimal> values) {
            addCriterion("F_ACTUALAMT in", values, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtNotIn(List<BigDecimal> values) {
            addCriterion("F_ACTUALAMT not in", values, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_ACTUALAMT between", value1, value2, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andFActualamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("F_ACTUALAMT not between", value1, value2, "fActualamt");
            return (Criteria) this;
        }

        public Criteria andSBcdnoIsNull() {
            addCriterion("S_BCDNO is null");
            return (Criteria) this;
        }

        public Criteria andSBcdnoIsNotNull() {
            addCriterion("S_BCDNO is not null");
            return (Criteria) this;
        }

        public Criteria andSBcdnoEqualTo(String value) {
            addCriterion("S_BCDNO =", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoNotEqualTo(String value) {
            addCriterion("S_BCDNO <>", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoGreaterThan(String value) {
            addCriterion("S_BCDNO >", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoGreaterThanOrEqualTo(String value) {
            addCriterion("S_BCDNO >=", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoLessThan(String value) {
            addCriterion("S_BCDNO <", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoLessThanOrEqualTo(String value) {
            addCriterion("S_BCDNO <=", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoLike(String value) {
            addCriterion("S_BCDNO like", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoNotLike(String value) {
            addCriterion("S_BCDNO not like", value, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoIn(List<String> values) {
            addCriterion("S_BCDNO in", values, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoNotIn(List<String> values) {
            addCriterion("S_BCDNO not in", values, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoBetween(String value1, String value2) {
            addCriterion("S_BCDNO between", value1, value2, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdnoNotBetween(String value1, String value2) {
            addCriterion("S_BCDNO not between", value1, value2, "sBcdno");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeIsNull() {
            addCriterion("S_BCDTYPE is null");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeIsNotNull() {
            addCriterion("S_BCDTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeEqualTo(String value) {
            addCriterion("S_BCDTYPE =", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeNotEqualTo(String value) {
            addCriterion("S_BCDTYPE <>", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeGreaterThan(String value) {
            addCriterion("S_BCDTYPE >", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeGreaterThanOrEqualTo(String value) {
            addCriterion("S_BCDTYPE >=", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeLessThan(String value) {
            addCriterion("S_BCDTYPE <", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeLessThanOrEqualTo(String value) {
            addCriterion("S_BCDTYPE <=", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeLike(String value) {
            addCriterion("S_BCDTYPE like", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeNotLike(String value) {
            addCriterion("S_BCDTYPE not like", value, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeIn(List<String> values) {
            addCriterion("S_BCDTYPE in", values, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeNotIn(List<String> values) {
            addCriterion("S_BCDTYPE not in", values, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeBetween(String value1, String value2) {
            addCriterion("S_BCDTYPE between", value1, value2, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSBcdtypeNotBetween(String value1, String value2) {
            addCriterion("S_BCDTYPE not between", value1, value2, "sBcdtype");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeIsNull() {
            addCriterion("S_ISSUERUSERCODE is null");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeIsNotNull() {
            addCriterion("S_ISSUERUSERCODE is not null");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeEqualTo(String value) {
            addCriterion("S_ISSUERUSERCODE =", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeNotEqualTo(String value) {
            addCriterion("S_ISSUERUSERCODE <>", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeGreaterThan(String value) {
            addCriterion("S_ISSUERUSERCODE >", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeGreaterThanOrEqualTo(String value) {
            addCriterion("S_ISSUERUSERCODE >=", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeLessThan(String value) {
            addCriterion("S_ISSUERUSERCODE <", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeLessThanOrEqualTo(String value) {
            addCriterion("S_ISSUERUSERCODE <=", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeLike(String value) {
            addCriterion("S_ISSUERUSERCODE like", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeNotLike(String value) {
            addCriterion("S_ISSUERUSERCODE not like", value, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeIn(List<String> values) {
            addCriterion("S_ISSUERUSERCODE in", values, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeNotIn(List<String> values) {
            addCriterion("S_ISSUERUSERCODE not in", values, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeBetween(String value1, String value2) {
            addCriterion("S_ISSUERUSERCODE between", value1, value2, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSIssuerusercodeNotBetween(String value1, String value2) {
            addCriterion("S_ISSUERUSERCODE not between", value1, value2, "sIssuerusercode");
            return (Criteria) this;
        }

        public Criteria andSOpenorgIsNull() {
            addCriterion("S_OPENORG is null");
            return (Criteria) this;
        }

        public Criteria andSOpenorgIsNotNull() {
            addCriterion("S_OPENORG is not null");
            return (Criteria) this;
        }

        public Criteria andSOpenorgEqualTo(String value) {
            addCriterion("S_OPENORG =", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgNotEqualTo(String value) {
            addCriterion("S_OPENORG <>", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgGreaterThan(String value) {
            addCriterion("S_OPENORG >", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgGreaterThanOrEqualTo(String value) {
            addCriterion("S_OPENORG >=", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgLessThan(String value) {
            addCriterion("S_OPENORG <", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgLessThanOrEqualTo(String value) {
            addCriterion("S_OPENORG <=", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgLike(String value) {
            addCriterion("S_OPENORG like", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgNotLike(String value) {
            addCriterion("S_OPENORG not like", value, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgIn(List<String> values) {
            addCriterion("S_OPENORG in", values, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgNotIn(List<String> values) {
            addCriterion("S_OPENORG not in", values, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgBetween(String value1, String value2) {
            addCriterion("S_OPENORG between", value1, value2, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andSOpenorgNotBetween(String value1, String value2) {
            addCriterion("S_OPENORG not between", value1, value2, "sOpenorg");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateIsNull() {
            addCriterion("TS_SYSUPDATE is null");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateIsNotNull() {
            addCriterion("TS_SYSUPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateEqualTo(Date value) {
            addCriterion("TS_SYSUPDATE =", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateNotEqualTo(Date value) {
            addCriterion("TS_SYSUPDATE <>", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateGreaterThan(Date value) {
            addCriterion("TS_SYSUPDATE >", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateGreaterThanOrEqualTo(Date value) {
            addCriterion("TS_SYSUPDATE >=", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateLessThan(Date value) {
            addCriterion("TS_SYSUPDATE <", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateLessThanOrEqualTo(Date value) {
            addCriterion("TS_SYSUPDATE <=", value, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateIn(List<Date> values) {
            addCriterion("TS_SYSUPDATE in", values, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateNotIn(List<Date> values) {
            addCriterion("TS_SYSUPDATE not in", values, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateBetween(Date value1, Date value2) {
            addCriterion("TS_SYSUPDATE between", value1, value2, "tsSysupdate");
            return (Criteria) this;
        }

        public Criteria andTsSysupdateNotBetween(Date value1, Date value2) {
            addCriterion("TS_SYSUPDATE not between", value1, value2, "tsSysupdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated do_not_delete_during_merge Sat May 16 12:16:44 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TV_TRADETAIL
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}