package com.aisino.finace.account.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TvTradetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_TRASRLNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal sTrasrlno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_CONNTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sConntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_MERACCT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sMeracct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_TERMCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sTermcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_TRANSTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sTranstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_CARDIOTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sCardiotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.D_TRANSDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private Date dTransdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.D_BALANCEDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private Date dBalancedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_TRANSAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fTransamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_MCC
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sMcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_HANDLCHARGDCTTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sHandlchargdcttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_FEERATIO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fFeeratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_FEERATIOAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fFeeratioamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_HANDLCHARGRATIOULMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fHandlchargratioulmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_HANDLCHARGRATIOLLMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fHandlchargratiollmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_HANDLCHARG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fHandlcharg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.F_ACTUALAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private BigDecimal fActualamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_BCDNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sBcdno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_BCDTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sBcdtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_ISSUERUSERCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sIssuerusercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.S_OPENORG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private String sOpenorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TV_TRADETAIL.TS_SYSUPDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    private Date tsSysupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_TRASRLNO
     *
     * @return the value of TV_TRADETAIL.S_TRASRLNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getsTrasrlno() {
        return sTrasrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_TRASRLNO
     *
     * @param sTrasrlno the value for TV_TRADETAIL.S_TRASRLNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsTrasrlno(BigDecimal sTrasrlno) {
        this.sTrasrlno = sTrasrlno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_CONNTYPE
     *
     * @return the value of TV_TRADETAIL.S_CONNTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsConntype() {
        return sConntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_CONNTYPE
     *
     * @param sConntype the value for TV_TRADETAIL.S_CONNTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsConntype(String sConntype) {
        this.sConntype = sConntype == null ? null : sConntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_MERACCT
     *
     * @return the value of TV_TRADETAIL.S_MERACCT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsMeracct() {
        return sMeracct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_MERACCT
     *
     * @param sMeracct the value for TV_TRADETAIL.S_MERACCT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsMeracct(String sMeracct) {
        this.sMeracct = sMeracct == null ? null : sMeracct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_TERMCODE
     *
     * @return the value of TV_TRADETAIL.S_TERMCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsTermcode() {
        return sTermcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_TERMCODE
     *
     * @param sTermcode the value for TV_TRADETAIL.S_TERMCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsTermcode(String sTermcode) {
        this.sTermcode = sTermcode == null ? null : sTermcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_TRANSTYPE
     *
     * @return the value of TV_TRADETAIL.S_TRANSTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsTranstype() {
        return sTranstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_TRANSTYPE
     *
     * @param sTranstype the value for TV_TRADETAIL.S_TRANSTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsTranstype(String sTranstype) {
        this.sTranstype = sTranstype == null ? null : sTranstype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_CARDIOTYPE
     *
     * @return the value of TV_TRADETAIL.S_CARDIOTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsCardiotype() {
        return sCardiotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_CARDIOTYPE
     *
     * @param sCardiotype the value for TV_TRADETAIL.S_CARDIOTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsCardiotype(String sCardiotype) {
        this.sCardiotype = sCardiotype == null ? null : sCardiotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.D_TRANSDATE
     *
     * @return the value of TV_TRADETAIL.D_TRANSDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public Date getdTransdate() {
        return dTransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.D_TRANSDATE
     *
     * @param dTransdate the value for TV_TRADETAIL.D_TRANSDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setdTransdate(Date dTransdate) {
        this.dTransdate = dTransdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.D_BALANCEDATE
     *
     * @return the value of TV_TRADETAIL.D_BALANCEDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public Date getdBalancedate() {
        return dBalancedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.D_BALANCEDATE
     *
     * @param dBalancedate the value for TV_TRADETAIL.D_BALANCEDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setdBalancedate(Date dBalancedate) {
        this.dBalancedate = dBalancedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_TRANSAMT
     *
     * @return the value of TV_TRADETAIL.F_TRANSAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfTransamt() {
        return fTransamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_TRANSAMT
     *
     * @param fTransamt the value for TV_TRADETAIL.F_TRANSAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfTransamt(BigDecimal fTransamt) {
        this.fTransamt = fTransamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_MCC
     *
     * @return the value of TV_TRADETAIL.S_MCC
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsMcc() {
        return sMcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_MCC
     *
     * @param sMcc the value for TV_TRADETAIL.S_MCC
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsMcc(String sMcc) {
        this.sMcc = sMcc == null ? null : sMcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_HANDLCHARGDCTTYPE
     *
     * @return the value of TV_TRADETAIL.S_HANDLCHARGDCTTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsHandlchargdcttype() {
        return sHandlchargdcttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_HANDLCHARGDCTTYPE
     *
     * @param sHandlchargdcttype the value for TV_TRADETAIL.S_HANDLCHARGDCTTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsHandlchargdcttype(String sHandlchargdcttype) {
        this.sHandlchargdcttype = sHandlchargdcttype == null ? null : sHandlchargdcttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_FEERATIO
     *
     * @return the value of TV_TRADETAIL.F_FEERATIO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfFeeratio() {
        return fFeeratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_FEERATIO
     *
     * @param fFeeratio the value for TV_TRADETAIL.F_FEERATIO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfFeeratio(BigDecimal fFeeratio) {
        this.fFeeratio = fFeeratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_FEERATIOAMT
     *
     * @return the value of TV_TRADETAIL.F_FEERATIOAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfFeeratioamt() {
        return fFeeratioamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_FEERATIOAMT
     *
     * @param fFeeratioamt the value for TV_TRADETAIL.F_FEERATIOAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfFeeratioamt(BigDecimal fFeeratioamt) {
        this.fFeeratioamt = fFeeratioamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_HANDLCHARGRATIOULMT
     *
     * @return the value of TV_TRADETAIL.F_HANDLCHARGRATIOULMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfHandlchargratioulmt() {
        return fHandlchargratioulmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_HANDLCHARGRATIOULMT
     *
     * @param fHandlchargratioulmt the value for TV_TRADETAIL.F_HANDLCHARGRATIOULMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfHandlchargratioulmt(BigDecimal fHandlchargratioulmt) {
        this.fHandlchargratioulmt = fHandlchargratioulmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_HANDLCHARGRATIOLLMT
     *
     * @return the value of TV_TRADETAIL.F_HANDLCHARGRATIOLLMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfHandlchargratiollmt() {
        return fHandlchargratiollmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_HANDLCHARGRATIOLLMT
     *
     * @param fHandlchargratiollmt the value for TV_TRADETAIL.F_HANDLCHARGRATIOLLMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfHandlchargratiollmt(BigDecimal fHandlchargratiollmt) {
        this.fHandlchargratiollmt = fHandlchargratiollmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_HANDLCHARG
     *
     * @return the value of TV_TRADETAIL.F_HANDLCHARG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfHandlcharg() {
        return fHandlcharg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_HANDLCHARG
     *
     * @param fHandlcharg the value for TV_TRADETAIL.F_HANDLCHARG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfHandlcharg(BigDecimal fHandlcharg) {
        this.fHandlcharg = fHandlcharg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.F_ACTUALAMT
     *
     * @return the value of TV_TRADETAIL.F_ACTUALAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public BigDecimal getfActualamt() {
        return fActualamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.F_ACTUALAMT
     *
     * @param fActualamt the value for TV_TRADETAIL.F_ACTUALAMT
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setfActualamt(BigDecimal fActualamt) {
        this.fActualamt = fActualamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_BCDNO
     *
     * @return the value of TV_TRADETAIL.S_BCDNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsBcdno() {
        return sBcdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_BCDNO
     *
     * @param sBcdno the value for TV_TRADETAIL.S_BCDNO
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsBcdno(String sBcdno) {
        this.sBcdno = sBcdno == null ? null : sBcdno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_BCDTYPE
     *
     * @return the value of TV_TRADETAIL.S_BCDTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsBcdtype() {
        return sBcdtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_BCDTYPE
     *
     * @param sBcdtype the value for TV_TRADETAIL.S_BCDTYPE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsBcdtype(String sBcdtype) {
        this.sBcdtype = sBcdtype == null ? null : sBcdtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_ISSUERUSERCODE
     *
     * @return the value of TV_TRADETAIL.S_ISSUERUSERCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsIssuerusercode() {
        return sIssuerusercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_ISSUERUSERCODE
     *
     * @param sIssuerusercode the value for TV_TRADETAIL.S_ISSUERUSERCODE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsIssuerusercode(String sIssuerusercode) {
        this.sIssuerusercode = sIssuerusercode == null ? null : sIssuerusercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.S_OPENORG
     *
     * @return the value of TV_TRADETAIL.S_OPENORG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public String getsOpenorg() {
        return sOpenorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.S_OPENORG
     *
     * @param sOpenorg the value for TV_TRADETAIL.S_OPENORG
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setsOpenorg(String sOpenorg) {
        this.sOpenorg = sOpenorg == null ? null : sOpenorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TV_TRADETAIL.TS_SYSUPDATE
     *
     * @return the value of TV_TRADETAIL.TS_SYSUPDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public Date getTsSysupdate() {
        return tsSysupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TV_TRADETAIL.TS_SYSUPDATE
     *
     * @param tsSysupdate the value for TV_TRADETAIL.TS_SYSUPDATE
     *
     * @mbggenerated Sat May 16 12:16:44 CST 2015
     */
    public void setTsSysupdate(Date tsSysupdate) {
        this.tsSysupdate = tsSysupdate;
    }
}